### DISCUSSION TITLE
How to remove "Open all in tabs"

### DISCUSSION THREAD

**Discussion by Kjaeremandag** [black7375/Firefox-UI-Fix#1004] [Q&A] [answered]
![Screenshot 2024-10-12 002306](https://github.com/user-attachments/assets/f5b9b4f8-6ce6-4a3b-ab34-edb97ee5aaab)
I've tried this but does not work, is there any way to remove it?
 .openintabs-menuitem,
.bookmarks-actions-menuseparator {
  display: none !important;
}

**Comment by Kjaeremandag** [comment]
No one?

**Comment by Mopslik** [comment, marked as answer]
For me works this:

.openintabs-menuseparator,
.openintabs-menuitem,
.bookmarks-actions-menuseparator 
    {  display: none !important; }

**Reply by Kjaeremandag** [reply]
Thank you for the reply, i was making that change  to userChrome, so today i tried to put it in leptonChrome and it worked!

**Comment by nademin** [comment]
Full How to guide:

Code from [Mozilla Support](https://support.mozilla.org/en-US/questions/945662#answer-393221) forum plus couple additions from [Mopslik](https://github.com/black7375/Firefox-UI-Fix/discussions/1004#discussioncomment-13734775)'s solution

Type `about:config` in the address bar and press Enter.
Search for `toolkit.legacyUserProfileCustomizations.stylesheets` and toggle it to `true`. This setting is required for `userChrome.css` to work

Type `about:support` in the address bar and press Enter.
Look for the Application Basics section.
Click on Open Profile Folder. This will open the folder where Firefox stores your user data.

In the Profile Folder, create a new folder and name it `chrome` (it may be already exist)
Inside the chrome folder, create a new blank file named `userChrome.css` (make sure that it is NOT `userChrome.css.txt`)
Place this code inside `userChrome.css` and restart your browser for the changes to take effect

```css
/* Hide Open All In Tabs Sub-Menu */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* Only needed once! */
#PlacesToolbarItems .openintabs-menuitem,
#PlacesToolbarItems .openintabs-menuseparator,
#PlacesToolbarItems .bookmarks-actions-menuseparator,
#placesContext>menuitem[id="placesContext_openContainer:tabs"],
#placesContext>menuitem[id="placesContext_openContainer:tabs"]:not([hidden])+menuitem+#placesContext_openSeparator {visibility:collapse!important}
```
