### DISCUSSION TITLE
My additional rules to fix many bugs when using auto hide nav-bar include bar un-hide before cursor reach and make the bar transparrent

### DISCUSSION THREAD

**Discussion by 117649** [black7375/Firefox-UI-Fix#1062] [Show and tell]
```css
@-moz-document url(chrome://browser/content/browser.xhtml){
@media (-moz-bool-pref: "userChrome.autohide.tabbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")),
(-moz-bool-pref: "userChrome.autohide.tabbar") and (-moz-bool-pref: "userChrome.tabbar.one_liner") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")),
(-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")),
(-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.tabbar.one_liner") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")) {

  /*  fix click through onto window frame when bar's hiding  */
  #mainPopupSet:not(:hover)~#navigator-toolbox:not(:hover, :focus-within) #nav-bar:not([customizing]) {
    -moz-window-dragging: no-drag;
  }

  /*  fix url bar un-hide before reach */
  #navigator-toolbox:not(:hover, :focus-within) #nav-bar:not([customizing]) #urlbar {
    pointer-events: none;
  }

  /* ctx menu hover unhide tool bars */
  #mainPopupSet:hover~#navigator-toolbox #nav-bar:not([customizing]),
  #mainPopupSet:hover~#navigator-toolbox #nav-bar:not([customizing]) #urlbar {
    opacity: 0.87;
    margin-bottom: 0;
  }

  #mainPopupSet:hover~#navigator-toolbox {
    --uc-toolbar-height: var(--uc-navbar-height);
  }

  /*   txt input trans */
  #navigator-toolbox:is(:hover, :focus-within) #nav-bar:not([customizing]) #urlbar {
    opacity: 0.87;
  }

  #navigator-toolbox #nav-bar:not([customizing]) #urlbar #urlbar-background {
    opacity: 0.95 !important;
    /*   background-color: color-mix(in srgb, var(--toolbar-field-focus-background-color) 90%, transparent) !important; */
  }

  #searchbar {
    opacity: 0.9 !important;
    /*   background-color: color-mix(in srgb, var(--toolbar-field-focus-background-color) 90%, transparent) !important; */
  }

  #PopupSearchAutoComplete {
    --panel-background: color-mix(in srgb, var(--toolbar-field-focus-background-color) 90%, transparent) !important;
  }

  /*   tool bar trans */
  #navigator-toolbox {
    background-color: transparent !important;
  }

  #navigator-toolbox>toolbar:nth-child(-n + 3) {
    background-color: var(--lwt-accent-color-inactive, var(--lwt-accent-color)) !important;
  }

  #PersonalToolbar:not([customizing]),
  #navigator-toolbox #nav-bar:not([customizing]) {
    background-color: color-mix(in srgb, var(--toolbar-bgcolor) 87%, transparent) !important;
  }
}

/*   fix nv bar hide when hover on tab bar */
toolbox#navigator-toolbox[id],
body,
:not(body) {
  --browser-stack-z-index-devtools-splitter: 2;
  --browser-stack-z-index-dialog-stack: 3;
  --browser-stack-z-index-rdm-toolbar: 4;
  --browser-area-z-index-toolbox: 1;
  --browser-area-z-index-sidebar: 2;
  --browser-area-z-index-tabbox: 3;
  --browser-area-z-index-sidebar-splitter: 4;
  --browser-area-z-index-toolbox-while-animating: 5;
}

#mainPopupSet:hover~#browser,
#navigator-toolbox:is(:hover, :focus-within)~#browser {
  z-index: 0;
}
}
```
