### DISCUSSION TITLE
Increase Sidebar Size

### DISCUSSION THREAD

**Discussion by KAGEYAM4** [black7375/Firefox-UI-Fix#519] [Q&A] [answered]
**Is your feature request related to a problem?**
I use sideberry , and i changed some of its internal available option, now the sidebar width seems o be small.

**The solution I'd like**
Any way to increase the sidebar width.
i tried this , by pasting it in `userContent.css` but did not worked.
```css
#sidebar {
	max-width: none !important;
	min-width: 0px !important; 
}
```

**Screenshots or video**
![image](https://user-images.githubusercontent.com/75798544/204617599-7b6bb405-590f-4339-82e6-07e9dff0f9dc.png)

**Comment by black7375** [comment, marked as answer]
I moved to discussions to separate bugs and usage inquiries.

---

Add to userChrome.css file:
```css
#sidebar-box {
  --uc-sidebar-activate-width: 18rem;
}
```
