### DISCUSSION TITLE
Found this code snippet to Totally Hide Sidebar and Unhide with mouse

### DISCUSSION THREAD

**Discussion by KAGEYAM4** [black7375/Firefox-UI-Fix#521] [Ideas]
```CSS
/*   Auto hide sidebar   */
#sidebar-box:not([hidden]) {
  border-right: solid 1px var(--chrome-content-separator-color) !important;
  box-shadow: 2px 0 14px rgba(0, 0, 0, 0.13) !important;
  overflow: hidden;
  height: 100%;
  position: fixed;
  min-width: 0 !important;
  max-width: 0 !important;
  display: block;
  z-index: 2;
  opacity: 0}

[sizemode=normal] #sidebar-box {max-width: 4px !important}

#appcontent {margin-left: -6px}

@media(-moz-windows-default-theme) {
  [sizemode=normal] #sidebar-box {height: calc(100% - 10px)}
  #appcontent {margin-left: 0}
}

#sidebar-box:not([hidden]):hover {
  width: 321px !important;
  max-width: 100% !important;
  opacity: 1}

#sidebar {
  width: 320px !important;
  height: 100%}


.sidebar-splitter {--sidebar-border-color: var(--chrome-content-separator-color)}

```

This is the [Repo](https://github.com/ongots/pseudo-fullscreen-firefox/blob/main/chrome/userChrome.css)
Having this in  `Firefox-UI-fix` would be great, as i still don't know the conflict . Currently managed it to work alongside with firefox-ui-fix
