### DISCUSSION TITLE
Change the font size of the tab and the font type.

### DISCUSSION THREAD

**Discussion by Brentolho** [black7375/Firefox-UI-Fix#796] [Q&A]
Hello, I wanted to know if I can add this function to increase the tab font size.

**Comment by black7375** [comment]
You can add following code at `userChrome.css`
```css
.tabbrowser-tab {
  font-size: 20px;
  font-family: serif;
}
```
