### DISCUSSION TITLE
container tab line

### DISCUSSION THREAD

**Discussion by gitfirl** [black7375/Firefox-UI-Fix#818] [Q&A] [answered]
how can i transfer the colored line in a container tab to the top?

![screenshot](https://github.com/black7375/Firefox-UI-Fix/assets/58876630/a9fa0773-a68b-464d-a1c8-88440d2c7ca6)

edit:

setting `userChrome.tab.container.on_top` to `true` in `user.js` did the trick.

i want the colored line at the very top though. how can i achieve that?

**Comment by black7375** [comment]
Okay, that looks too close to the center.
Now I've [adjust the value](https://github.com/black7375/Firefox-UI-Fix/commit/d3e90314f0794396c020521715866eee0a8dfcce) to make it look better. How does it look?

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/c4bd05e8-80ea-4a55-acde-de6a0595d10d)

**Reply by black7375** [reply]
Or you can add to `userChrome.css`.

```css
@media (-moz-bool-pref: "userChrome.tab.container") and (not (-moz-bool-pref: "userChrome.tabbar.as_titlebar")) and (-moz-bool-pref: "userChrome.tab.container.on_top") {
  #tabbrowser-tabs {
    --uc-container-position-y: calc(50% - var(--tab-min-height) / 2);
  }
}
```

**Reply by gitfirl** [reply]
thanks for helping!

i ended up setting `userChrome.tab.container` to `false`. i think i like it the most. just one thing, how can i make the colored lines look thicker?

![ss](https://github.com/black7375/Firefox-UI-Fix/assets/58876630/7a76febb-6ada-416f-909f-7c430a6b299f)

(btw, i'm using firefox 115.4.0esr, if that matters.)

**Reply by black7375** [reply, marked as answer]
Try to add `userChrome.css` with this code.
```css
.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
  height: 4px !important;
}
```
