### DISCUSSION TITLE
How to change background colour of utility menu?

### DISCUSSION THREAD

**Discussion by Beleth-D** [black7375/Firefox-UI-Fix#895] [Q&A]
Hello everyone,
how to change background colour of utility menu? 
Thanks ❤️

![screensht_24-05-19_02 03 23](https://github.com/black7375/Firefox-UI-Fix/assets/167132067/5618c7b4-dccd-4847-b52c-03505a81bf7e)

**Comment by black7375** [comment]
Are you modifying userChrome.css and not the theme?
Consider utilizing the following code
```css
#main-window {
  --arrowpanel-background: red !important;
  --arrowpanel-color: blue !important;
  --arrowpanel-border-color: yellow !important;
}
```
