### ISSUE TITLE
Broken box shadow at bottom right corners

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#1]
![firefox_proton_bottom_round_red](https://user-images.githubusercontent.com/25581533/116497793-b5e2cd80-a897-11eb-92ec-061d4c648c5e.png)

**Comment by black7375** [comment]
I removed this.

```css
  /* Selected Tab - Bottom Rounded Corner */
  /* Bottom corner rounding for tabs, Remove this section if your tab bottom corners look bad */

  tab {
    --tab-corner-rounding: 8px;
    --animation-speed: 0.15s;
  }

  tab[visuallyselected] .tab-background::before,
  tab[visuallyselected] .tab-background::after {
    content: "" !important;
    display: inline !important;
    position: absolute !important;
    width: var(--tab-corner-rounding) !important;
    height: var(--tab-corner-rounding) !important;
    bottom: -1px !important;
    pointer-events: none !important;
    background-color: transparent !important;
    transition: var(--animation-speed) !important;
  }

  tab[visuallyselected] .tab-background::before {
    border-bottom-right-radius: var(--tab-corner-rounding) !important;
    transform: translateX(calc(-1 * var(--tab-corner-rounding))) !important;
    box-shadow: 0 1px 1px -1px var(--toolbar-color), /* <- Selected Box Shadow */
                4px 4px 0px 4px var(--toolbar-bgcolor) !important;
    transition: var(--animation-speed) !important;
  }

  tab[visuallyselected] .tab-background::after {
    border-bottom-left-radius: var(--tab-corner-rounding) !important;
    right: 0px !important;
    transform: translateX(calc(var(--tab-corner-rounding) + 1px)) !important;
    box-shadow: -1px 0 0 -1px var(--toolbar-color), /* <- Selected Box Shadow */
                -4px 4px 0px 4px var(--toolbar-bgcolor) !important;
    transition: var(--animation-speed) !important;
  }

```
