### ISSUE TITLE
Pls make the topsites letter center aligned

### ISSUE THREAD

**Issue by Hochiss** [black7375/Firefox-UI-Fix#106]
![Screen Shot 2021-06-23 at 12 07 24](https://user-images.githubusercontent.com/36304198/123078996-cfc60a00-d41b-11eb-9f58-7676d0417b93.png)

The big letters are a bit down/bottom, would you please or how to make it center/middle aligned? thanks!

**Comment by black7375** [comment]
Try this.
```css
  @-moz-document url("about:home"), url("about:newtab") {
    .top-site-outer .tile .icon-wrapper.letter-fallback::before {
      top: 0px; /* Original: 6px */
    }
  }
```

**Comment by Hochiss** [comment]
thanks but not working, even putting `!important` at the padding `top: 0px;` 
at the end the first section of `@-moz-document url("about:home"), url("about:newtab") {`:

```
    .top-site-outer .tile .icon-wrapper.letter-fallback::before { 
      top: 0px; !important; /* Original: 6px */
    }
```

Seems the 6px padding cannot be overridden?:

![Screenshot 2021-06-24 at 09 41 39](https://user-images.githubusercontent.com/36304198/123223670-5ee12980-d4d1-11eb-89c6-b176ce0ca64c.png)

**Comment by black7375** [comment]
`important!` code has been added.

Before
![image](https://user-images.githubusercontent.com/25581533/123272122-fbff8a80-d4f0-11eb-8eb1-65b64401504d.png)

After
![image](https://user-images.githubusercontent.com/25581533/123272089-f43fe600-d4f0-11eb-9f89-1f943b32b865.png)

It works fine.

---

I want to keep the current design.
In the case of capital letters, the center of gravity is at the top, so it is more stable than perfectly centered.

**Comment by Hochiss** [comment]
strange still not working for me! I have put your 2 css into profile/chrome already.

**Comment by black7375** [comment]
It must be in `userContent.css`  file.

**Comment by Hochiss** [comment]
this is the first section of chrome\userContent.css: 
```
@media (-moz-proton) {
  @-moz-document url("about:home"), url("about:newtab") {
    /** Activity Stream - Search Focus Border: like URL ***********************/
    /* At DarkMode, Color */
    body[style*="--newtab-background-color:rgba(28, 27, 34, 1);"],
    body[style*="--newtab-background-color:rgba(42, 42, 46, 1);"],
    body[style*="--newtab-background-color: rgba(42, 42, 46, 1);"] {
      /* inner */
      --newtab-focus-border: rgba(0, 221, 255, 0.5) !important; /* Original: #B5D3FF, Better color-mix(in srgb, #B5D3FF 70%, transparent) */
      --newtab-focus-border-selected: rgba(0, 221, 255, 0.5) !important; /* Original: #B5D3FF */
    }

    /** Activity Stream - Web Site Icon: full size ****************************/
    .top-site-outer .tile .icon-wrapper {
      width:  100% !important; /* Original: 48px */
      height: 100% !important; /* Original: 48px */
    }
    .top-site-outer .tile .icon-wrapper.letter-fallback::before {
      top: 0px; !important; /* Original: 6px */
    }
  }



```

**Comment by black7375** [comment]
> anything wrong there?

There is one more semicolon.
```css
    .top-site-outer .tile .icon-wrapper.letter-fallback::before {
      top: 0px; !important; /* Original: 6px */
    }
```

=>
```css
    .top-site-outer .tile .icon-wrapper.letter-fallback::before {
      top: 0px !important; /* Original: 6px */
    }
```
