### ISSUE TITLE
Disable Address bar fade effect

### ISSUE THREAD

**Issue by mStirner** [black7375/Firefox-UI-Fix#1061]
### Is your feature request related to a problem?

Since the update to v133.0.3, the browser address bar has a transition effect on the background of the address bar.

### The solution I'd like

I would like that it has it full color/alpha channel from the begin, when i click in the address bar.

### Alternatives I've considered

Asked ChatGPT about the problem, and is suggested to add custom css rules to chrome.css
```css
/** Import Lepton stylesheet (Chrome) *****************************************/
@import url("css/leptonChrome.css");


/** Add your custom styles below **********************************************/

/* Enable option to edit bookmark URLs under Add Bookmark (blue star) menu */
/*
.editBMPanel_locationRow {
  display: initial !important;
}
*/

/* Disable Email Image/Audio/Video and Set as Desktop Background context menu items */
/*
#context-sendimage,
#context-sendvideo,
#context-sendaudio,
#context-sep-setbackground,
#context-setDesktopBackground {
  display: none !important;
}
*/

#urlbar {
    transition: none !important;
}
```

But `#urlbar{...}` did nothing and the effect is still present.
