### ISSUE TITLE
Active tab background is too wide and can be seen from the sides of the tab

### ISSUE THREAD

**Issue by failsafe42** [black7375/Firefox-UI-Fix#141]
![image](https://user-images.githubusercontent.com/40743506/128950342-87539bb9-73e1-4883-bf75-39f60caabbbf.png)

It currently looks like the picture above and I expect it to look like the picture below.

![image](https://user-images.githubusercontent.com/40743506/128950522-05859e09-a6e2-4f59-8c88-4c475e1150be.png)

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129031396-662bfc9b-88dd-48b6-8c67-c67d75317a1a.png)
It's slightly larger than the edge, so I think it's fine.

Changed to `Proton` and the overall menu has grown.
I increased the width of the tabs for balance, which has three more advantages.
- The area increases, making it easier to click.
- As the tab increases, it reaches the end faster, so the new tab button is more likely to be fixed.
- Visually balanced with Proton.

---

If you don't like this change, you can try deleting the next lines.
https://github.com/black7375/Firefox-UI-Fix/blob/81f195f7e4cf443371ce465ea2936aa2a4ce7709/userChrome.css#L484-L486

**Comment by failsafe42** [comment]
The problem isn't the tab being too wide, it's the background that's too wide. There are blue lines to the sides of the active tab when it should only be blue above the tab.

**Comment by black7375** [comment]
Perhaps adding the following code will solve it.

```css
#TabsToolbar[brighttext] #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected="true"], [multiselected]) > .tab-stack > .tab-background:-moz-lwtheme {
  --tabs-border-color: rgba(0,0,0,.3) !important;
  box-shadow: 0 0 1px var(--tabs-border-color) !important; /* Original: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9)) */
}
#TabsToolbar:not([brighttext]) #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected="true"], [multiselected]) > .tab-stack > .tab-background {
  box-shadow: 0 0 1px var(--tabs-border-color), 0 0 4px rgba(128,128,142,0.5) !important; /* Original: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9)), 0 0 4px rgba(128,128,142,0.5) */
}
```

The current tab also looks good, so I'm thinking about it.
