### ISSUE TITLE
remove strip

### ISSUE THREAD

**Issue by 82d** [black7375/Firefox-UI-Fix#148]
how to remove a shitty strip? thanks.
![5](https://user-images.githubusercontent.com/15121782/129105537-7c69cb75-cab8-4f15-9aa6-07a073cffb93.png)

**Comment by black7375** [comment]
It's easy.

```css
#appMenu-fxa-separator {
  display: none;
}
```

![image](https://user-images.githubusercontent.com/25581533/129120364-98ab6244-a0f3-4b87-b5c5-2963b5405a75.png)
