### ISSUE TITLE
Reduce de size of the "close tab" square

### ISSUE THREAD

**Issue by TB54** [black7375/Firefox-UI-Fix#179]
Hello everyone, and thank you so much for this theme which helped me to not leave firefox for another browser after proton ! Sorry for my english, not my native language...

It seems pretty close to the ancient firefox version, except one thing : the clickable square around the "close tab cross" seems very large: 

![](https://i.imgur.com/ERseJVo.jpeg)

I noticed it because i keep closing tabs by accident when i just want to click on them (to select them) : the closing-tab area takes almost one third of the all tab when they are many and that they are short. I don't have the ancient version of firefox to compare, but it seems to me this square was more tiny, pretty much the size of the cross itself.

**Comment by BPower0036** [comment]
Yes, maybe that background square on hover can made smaller. That would be nice.

**Comment by skynick11** [comment]
> I noticed it because i keep closing tabs by accident when i just want to click on them (to select them) 

Yes, you a right. You also can compare the same field in Edge (left) and Firefox (right).

![изображение](https://user-images.githubusercontent.com/37669204/130095894-48fb6dd6-fd22-4e31-a852-d2a711ad8276.png)

**Comment by black7375** [comment]
How about this size?
![image](https://user-images.githubusercontent.com/25581533/130184868-b4228113-4c81-49d5-b2e8-aeef433d26fd.png)

```css
.tab-content > .tab-close-button {
  padding: 5px !important; /* Original: 7px */
  width:  20px !important; /* Original: 24px */
  height: 20px !important; /* Original: 24px */
}
.tabbrowser-tab:not(:hover) > .tab-stack > .tab-content > .tab-close-button {
  padding-inline-start: 2px !important; /* Original: 0px */
  width: 17px !important; /* Original: 17px = (width - padding), for !important */
}
```

**Comment by BPower0036** [comment]
Great, for me thsi size is fine!!!

**Comment by skynick11** [comment]
> How about this size?

The size of the field is ok, but it's also needed to increase the size of the "x" symbol (in FF78 it was large, so the space between the "x" and a border of the "square" was smaller, that's why it was "harder" to close the tab accidentally):

![изображение](https://user-images.githubusercontent.com/37669204/130200385-121f70b9-353c-46b7-a24d-7d5df3472612.png)

**Comment by BPower0036** [comment]
@skynick11 I found the right "x" symbol too big. Maybe we can get something between the left en right size of the "x" symbol

**Comment by BPower0036** [comment]
Maybe something like this

`/** TAB CLOSE BUTTON **/`
`.tabbrowser-tab .tab-content > .close-icon {`
`  list-style-image: url(icons/close.svg) !important;`
`}`

close.svg is:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16" style="fill: context-fill; fill-opacity: context-fill-opacity;" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16">`
`  <g>`
`    <path d="m0.147,0.31572l0.073,-0.084a0.75,0.75 0 0 1 0.976,-0.073l0.084,0.073l6.47,6.469l6.47,-6.47a0.75,0.75 0 1 1 1.06,1.061l-6.469,6.47l6.47,6.47a0.75,0.75 0 0 1 0.072,0.976l-0.073,0.084a0.75,0.75 0 0 1 -0.976,0.073l-0.084,-0.073l-6.47,-6.469l-6.47,6.47a0.75,0.75 0 0 1 -1.06,-1.061l6.469,-6.47l-6.47,-6.47a0.75,0.75 0 0 1 -0.072,-0.976l0.073,-0.084l-0.073,0.084z"/>`
`  </g>`
`</svg>`

**Comment by skynick11** [comment]
>  I found the right "x" symbol too big.

![изображение](https://user-images.githubusercontent.com/37669204/130219967-2452b726-c7e6-4c83-b72b-7cb689defa44.png)

from left to right:
1. close button after https://github.com/black7375/Firefox-UI-Fix/issues/179#issuecomment-902445056 
2. my close button with browser.proton.enabled=false and browser.compactmode.show=true (in the FF where it was possible to disable proton)
3. close button in Edge Chromium (I don't use Chrome)
4. close button before https://github.com/black7375/Firefox-UI-Fix/issues/179#issuecomment-902445056 
5. close button in FF78 from #173

As I can see,
- in 1 the "x" symbol has the same size as in 3 (except visual effects like "white on black vs black on white"- it's possible to think that they have different sizes :) ), but the size of the square field around it is larger then in 3.
- in 2 and 5 the "x" symbol has the same size (but with different thickness)
- in 1, 3 and 4 the "x" symbol is lesser then in 2 and 5.

So, there are two ways:
- to increase the "x" symbol (up to FF78 one, for example).
- to decrease the size of the square field (down to Edge one, for example).
Or to use both ways ;)

p.s. I'll check https://github.com/black7375/Firefox-UI-Fix/issues/179#issuecomment-902561724 later, right now I have no ability to test it.

**Comment by TB54** [comment]
The third one seems the best to me, but I must be biased by the 5867547th tab I accidentally closed this morning and would go for the smaller anyway :-)

**Comment by black7375** [comment]
Results after some adjustments
- Spacing is sufficient
![image](https://user-images.githubusercontent.com/25581533/130225326-0309b2ff-6cec-45a6-a87c-89804ac876d1.png)
- Spacing is insufficient
![image](https://user-images.githubusercontent.com/25581533/130225431-ed978e8f-0a27-47ad-8ff6-2da037c7976b.png)


```css
.tabbrowser-tab:not(:hover) > .tab-stack > .tab-content > .tab-close-button {
  padding-inline-start: 1px !important; /* Original: 0px */
  width: 19px !important; /* Original: 17px */
}
.tab-close-button {
  padding: 6px !important; /* Original: 7px */
}

#tabbrowser-tabs[closebuttons="activetab"] .tab-content > .tab-close-button {
  margin-inline-end: calc((var(--inline-tab-padding) / -2) + 2px) !important; /* Original: calc(var(--inline-tab-padding) / -2)*/
  padding: 4px !important; /* Original: 7px */
  width:  20px !important; /* Original: 24px */
  height: 20px !important; /* Original: 24px */
}
#tabbrowser-tabs[closebuttons="activetab"] .tabbrowser-tab:not(:hover) > .tab-stack > .tab-content > .tab-close-button {
  padding-inline-start: 3px !important; /* Original: 0px */
  width: 19px !important; /* Redefine from 20px !important, Original: 17px = (width - padding)  */
}
```

**Comment by BPower0036** [comment]
>     * in 1 the "x" symbol has the same size as in 3 (except visual effects like "white on black vs black on white"- it's possible to think that they have different sizes :) ), but the size of the square field around it is larger then in 3.
> 
> p.s. I'll check [#179 (comment)](https://github.com/black7375/Firefox-UI-Fix/issues/179#issuecomment-902561724) later, right now I have no ability to test it.

I didn't know they where the same. The close button in Edge did look a little bit thicker to me then Firefox close button.

**Comment by skynick11** [comment]
> I didn't know they where the same. The close button in Edge did look a little bit thicker to me then Firefox close button.

![изображение](https://user-images.githubusercontent.com/37669204/130231531-043a832d-bed3-4b7c-a1bf-b494e2f927d5.png)

Hmmm... Yes. Edge's "X" is larger on 1 pixel, but square around it is smaller on 3 pixels...

**Comment by black7375** [comment]
- Firefox Icon
![image](https://user-images.githubusercontent.com/25581533/130231794-45fee1ba-b2e5-4c7e-91d6-0b4bc7689080.png)
- Edge Icon
![image](https://user-images.githubusercontent.com/25581533/130231709-c3c98b75-5508-48b7-a6b6-8162e9fcab17.png)
  - https://github.com/microsoft/fluentui-system-icons/blob/master/assets/Dismiss/SVG/ic_fluent_dismiss_16_filled.svg?short_path=3f00344


Code:
```css
.tabbrowser-tab .tab-content > .close-icon {
  list-style-image: url("data:image/svg+xml,%3Csvg width='16' height='16' viewBox='0 0 16 16' style='fill: context-fill; fill-opacity: context-fill-opacity;' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M2.39705 2.55379L2.46967 2.46967C2.73594 2.2034 3.1526 2.1792 3.44621 2.39705L3.53033 2.46967L8 6.939L12.4697 2.46967C12.7626 2.17678 13.2374 2.17678 13.5303 2.46967C13.8232 2.76256 13.8232 3.23744 13.5303 3.53033L9.061 8L13.5303 12.4697C13.7966 12.7359 13.8208 13.1526 13.6029 13.4462L13.5303 13.5303C13.2641 13.7966 12.8474 13.8208 12.5538 13.6029L12.4697 13.5303L8 9.061L3.53033 13.5303C3.23744 13.8232 2.76256 13.8232 2.46967 13.5303C2.17678 13.2374 2.17678 12.7626 2.46967 12.4697L6.939 8L2.46967 3.53033C2.2034 3.26406 2.1792 2.8474 2.39705 2.55379L2.46967 2.46967L2.39705 2.55379Z'/%3E%3C/svg%3E") !important;
}
```

I like this quite a bit.
