### ISSUE TITLE
Coloured folder icons in bookmarks menu

### ISSUE THREAD

**Issue by maboroshix** [black7375/Firefox-UI-Fix#20]
**Feature request.**
First and foremost, thank you very much for this black7375! It's a very nice layout and redesign tweaking + blending of Photon and Proton. The bookmarks icon has changed to an outline of the folder instead of the fill in coloured version I had previously. Is there a relatively pain free fix for this?

**Describe the solution you'd like**
Revert back to filled in bookmarks folder icon, as opposed to the outlined version introduced in Proton.

**Comment by black7375** [comment]
Do you mean like this?
**Before - After**
![before bookmark image](https://user-images.githubusercontent.com/25581533/120405179-86602e80-c337-11eb-9958-b7c509a5d1f5.png)

![after boomark image](https://user-images.githubusercontent.com/25581533/120405159-79dbd600-c337-11eb-9d41-c964709aaf2c.png)

**Code**
```css
#bookmarks-menu-button {
  list-style-image: url(chrome://browser/skin/bookmark.svg) !important;
}
```
