### ISSUE TITLE
Menu bar shifts when clicked

### ISSUE THREAD

**Issue by Jonas1312** [black7375/Firefox-UI-Fix#207]
**Describe the bug**

Menu bar moves down when I click on a menu.

**Expected behavior**

Shouldn't shift down.

**Screenshots**

![Animation](https://user-images.githubusercontent.com/15847892/131705711-ad23a360-ed9d-4871-8899-1cfeb4025bb1.gif)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Please check it out.

**Comment by black7375** [comment]
Could you try this code?

```css
  #toolbar-menubar {
    display: flex !important;
    justify-content: space-between;
    flex-direction: row;
  }
  #toolbar-menubar > spacer {
    order: 1000; /* as Original's -moz-box-ordinal-group: 1000 */
    flex: 1; /* Fill row */
  }
  #toolbar-menubar > .titlebar-buttonbox-container {
    order: 1000; /* as Original's -moz-box-ordinal-group: 1000 */
  }
```

**Comment by Jonas1312** [comment]
Should I keep the previous commit 0513ffd? Like that:

userChrome.css:
```css
  /*= Global Menu - Set Padding ==============================================*/
  /* Vertical Align - Center & Height: 100%  */
  #menubar-items,
  #main-menubar {
    display: flex !important;
  }
  
  #toolbar-menubar {
    display: flex !important;
    justify-content: space-between;
    flex-direction: row;
  }
  #toolbar-menubar > spacer {
    order: 1000; /* as Original's -moz-box-ordinal-group: 1000 */
    flex: 1; /* Fill row */
  }
  #toolbar-menubar > .titlebar-buttonbox-container {
    order: 1000; /* as Original's -moz-box-ordinal-group: 1000 */
  }
```
