### ISSUE TITLE
Windows 7 minimize maximize close buttons hidden

### ISSUE THREAD

**Issue by picollo7** [black7375/Firefox-UI-Fix#218]
**Describe the bug**

In Windows 7 the minimize, maximize, and close buttons are covered by the background image in dark mode.  They still work, but are not visible.

**Expected behavior**

The minimize, maximize, and close buttons should be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/90575777/133000889-9839fb9a-7339-4d1c-9a5c-61c9910f89ed.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Would you like to upgrade to a lastest commit?

**Comment by jskm** [comment]
This issue is caused by changes in Firefox. I see it with Firefox 92 running on Windows 7 with Aero.

I tried earlier versions of Lepton until v1.0 before getting the titlebar buttons visible again. It is d16cd6d that makes the navigator-toolbox opaque and ends up blocking the titlebar buttons, but I've been using much newer versions than that without problems, so the difference had to be a Firefox update.

I downloaded Firefox 90, 91, and the 91.1 ESR, and narrowed down the change to sometime after 91.0.2. In fact, even unaltered, Firefox 92 and 91.1.0esr paint over the title bar buttons as shown in the second image here:

### Firefox 91.0.2:
![Firefox-91 0 2](https://user-images.githubusercontent.com/4820827/133936138-864dae09-ff37-47e2-b21c-3350689ad0f5.png)

### Firefox 91.1.0esr:
![Firefox-91 1 0esr](https://user-images.githubusercontent.com/4820827/133936140-fc3bb85a-137e-4a66-8720-70313c809dfc.png)

While toggling properties in the Browser Toolbox, I found that everything went back to normal, even having Aero transparency in the title bar again, after removing this setting introduced in d16cd6d:

https://github.com/black7375/Firefox-UI-Fix/blob/a96fab298cc978d55c762ae139fc3a4896a9c651/userChrome.css#L80-L82

### Lepton, fixed:
![Firefox-ESR-Lepton](https://user-images.githubusercontent.com/4820827/133936174-f1164613-bed0-4b6d-875b-640ae893f84c.png)

It seems `#TabsToolbar { background-image: unset !important }` is what removes the broken coloration of the tab bar seen in default Firefox. To change the background of the tab bar as before, you'd have to be able to cut out a transparent region over the title bar buttons.

**Comment by black7375** [comment]
Based on the latest commit, the symptom does not appear.
![image](https://user-images.githubusercontent.com/25581533/133938799-1e73fd1a-b353-4247-96e8-4e52c1193211.png)

**Comment by jskm** [comment]
I downloaded the portable version of Firefox 92, ran it, and then installed the latest commit for Lepton. Without Lepton, the tab bar has the white overlay painted over the title bar buttons, as shown in my previous screenshot. With Lepton, it looks correct with Aero transparency and visible system buttons, until I go to Customize Toolbar -> Themes and choose the Light or Dark theme. Then the system buttons are painted over completely.

It turns out that the "System theme" setting works correctly, but I've never used it because it is light-themed on Windows 7. The Firefox Dark theme still does not seem to work, showing the problem as described in the first post. I've just discovered the ui.systemUsesDarkTheme option in combination with the Firefox System theme which does work as intended. Though it seems there's transparency if ui.systemUsesDarkTheme is set for light mode, and solid color when set to dark.

**Comment by black7375** [comment]
Looks like I found a workaround yesterday.
https://www.reddit.com/r/waterfox/comments/qk0rjz/waterfox_g4_themes/hjakxzs/?context=3

Download [ff_win7_darkmode.reg](https://gist.githubusercontent.com/black7375/12852a63bd1d355dbdd3c2a723b29328/raw/5849f55c57651abf756042715c9d9c078103e3e4/ff_win7_darkmode.reg) and double-clicking on it.

Does it works?

**Comment by Kiki79250CoC** [comment]
OK. This reg fix partially fixes the problem. Let me explain.

- When I use the System theme, It works (Image 1)
- When I use one of the newest theme introduced with Firefox 94, it Works (Image 2 & 3)
- But When I use the "full" Dark and Light theme, it doesn't work (Image 4 & 5).

(Image 1 :)
![image](https://user-images.githubusercontent.com/54137141/143735628-93b38779-ea76-4390-b4af-01f061a5938a.png)

(Image 2 :)
![image](https://user-images.githubusercontent.com/54137141/143735769-c507a307-9205-4414-bbaa-40b70edd5057.png)

Image 3 :)
![image](https://user-images.githubusercontent.com/54137141/143735822-2f534613-5a58-40f8-b9b0-a97bb1d694a6.png)

(Image 4 :)
![image](https://user-images.githubusercontent.com/54137141/143735866-5b6356e2-04ec-4a85-84fd-59577016e57a.png)

(Image 5 :)
![image](https://user-images.githubusercontent.com/54137141/143735955-0df628c8-2114-4c39-9720-b089355b3765.png)

I remember that before Firefox 89, only tabs back have the color, leaving the whole window have the Aero (Here in Firefox 90.0.2 with Ptoton Disabled) :
![image](https://user-images.githubusercontent.com/54137141/143755908-b9c7f369-c47c-4f0c-84af-60eeb41fe76a.png)

**Comment by black7375** [comment]
@Kiki79250CoC 

Thank you very much for doing a lot of testing.
Can you attach the `about:support - Copy text to clipboard` information for reproduction?

**Comment by Kiki79250CoC** [comment]
Here is the content of the clipboard after clicking the button : 
(if you can't find the info I snapped the whole page here : [about config page.zip](https://github.com/black7375/Firefox-UI-Fix/files/7613674/about.config.page.zip))

<html><body>


      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="app-basics-title">Paramètres de base de l’application</h2>

      

Nom | Firefox
-- | --
94.0.2
20211119140621
 
release
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
Windows_NT 6.1 7601
Activé
1/1
0/1               Désactivées par défaut
11
Inactives
Présente
Présente
Présente
false



    
</body>
</html>

**Comment by black7375** [comment]
I just tried it, and the pasting comes out weird.
I'm sorry, but can you do it again with `Copy raw data to clipboard`?

**Comment by Kiki79250CoC** [comment]
I put the raw data in a text file :
[Raw data.txt](https://github.com/black7375/Firefox-UI-Fix/files/7613682/Raw.data.txt)

**Comment by black7375** [comment]
Reproducibility is quite difficult.
![Win7-2021-12-01-12-07-43](https://user-images.githubusercontent.com/25581533/144227028-dc28df88-ce87-456d-b735-cfcf10e8f7c5.png)

However, once I applied a patch that could solve it. https://github.com/black7375/Firefox-UI-Fix/commit/8a8351de928c95ed482955f989ba48eba4f20ba4
I'm not sure if it can be solved. A test is required.

**Comment by black7375** [comment]
I followed the color-way renders.
This time, I predict that the symptoms will probably go away.

---
I was working on following the default theme of Win7, but found that it was not applied in color-way.

If an option system is adopted in the future, we are going to add an option to forcibly activate the Win7 default like theme.
(Just for memo)

```css
/*= Windows 7, 8 - Tab Bar Background *****************************************/
@media (-moz-os-version: windows-win7) {
  /* Header Color */
  :root:not([lwtheme-image]):-moz-lwtheme #menubar-items,
  :root:not([lwtheme-image]):-moz-lwtheme .tab-background:not([selected], [multiselected]),
  :root:not([lwtheme-image]):-moz-lwtheme #titlebar .toolbarbutton-1 > .toolbarbutton-icon,
  :root:not([lwtheme-image]):-moz-lwtheme #alltabs-button > .toolbarbutton-badge-stack,
  #scrollbutton-up:-moz-lwtheme,
  #scrollbutton-down:-moz-lwtheme {
    background-color: var(--lwt-accent-color) !important;
  }

  :root:not([lwtheme-image]):-moz-lwtheme .tabbrowser-tab:hover > .tab-stack > .tab-background:not([selected], [multiselected]),
  :root:not([lwtheme-image]):-moz-lwtheme #titlebar .toolbarbutton-1:hover > .toolbarbutton-icon,
  :root:not([lwtheme-image]):-moz-lwtheme #alltabs-button:hover > .toolbarbutton-badge-stack,
  #scrollbutton-up:-moz-lwtheme:hover,
  #scrollbutton-down:-moz-lwtheme:hover {
    background-color: color-mix(in srgb, currentColor 15%, var(--lwt-accent-color)) !important;
  }
  :root:not([lwtheme-image]):-moz-lwtheme #titlebar .toolbarbutton-1:is([open], :hover:active) > .toolbarbutton-icon,
  :root:not([lwtheme-image]):-moz-lwtheme #alltabs-button:is([open], :hover:active) > .toolbarbutton-badge-stack,
  #scrollbutton-up:-moz-lwtheme:hover:active,
  #scrollbutton-down:-moz-lwtheme:hover:active {
    background-color: color-mix(in srgb, currentColor 20%, var(--lwt-accent-color)) !important;
  }

  #TabsToolbar:-moz-lwtheme {
    color: var(--lwt-text-color) !important;
  }

  /* Remove Aero */
  #TabsToolbar {
    /* Original: radial-gradient(eclipse at bottom, rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.5) 80%, transparent) */
    background-image: unset !important;
  }
}
@media (-moz-os-version: windows-win8) {
  /* Header Color */
  :root:not([lwtheme-image]):-moz-lwtheme {
    background-color: var(--lwt-accent-color) !important;
  }

  #navigator-toolbox:-moz-lwtheme {
    color: var(--lwt-text-color) !important;
  }
}
```
