### ISSUE TITLE
Weird behavior of reduce/maximise/quit buttons

### ISSUE THREAD

**Issue by Jonas1312** [black7375/Firefox-UI-Fix#219]
**Describe the bug**
Sometimes, reduce/maximise/quit buttons move to the left. This bug appears randomly.

When I move my mouse over the buttons, they instantly go back to the right place as shown in the gif below.

**Expected behavior**
Buttons should stay on the right

**Screenshots**

![Animation](https://user-images.githubusercontent.com/15847892/133049002-ff1f208b-5134-41f6-98db-37e055d04fa1.gif)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Is the menu bar active?
![image](https://user-images.githubusercontent.com/25581533/133050525-3922a0d6-a845-4f01-8d8b-491b57d4348b.png)

**Comment by Jonas1312** [comment]
yes

**Comment by black7375** [comment]
It's really hard to reproduce this.
Does anyone know exactly in what environment and under what situation?

**Comment by Jonas1312** [comment]
Yeah, it's hard to reproduce... I tried with last commit https://github.com/black7375/Firefox-UI-Fix/commit/88a323b8479fdd6cff580f36873f7620bcf50131, and I still have the bug.

I'll try with the code below now
```css
#toolbar-menubar .titlebar-button {
  padding-block: 0px !important;
}
```

**Comment by Jonas1312** [comment]
Still not working...
![Untitled](https://user-images.githubusercontent.com/15847892/133732930-00f424f3-b0bf-4da7-8b6f-ef61d3312719.png)

I'll try to find the faulty commit during the next few days

**Comment by Jonas1312** [comment]
When I checkout on 0513ffd9 the bug does not appear. When I checkout on 7ddef19c the bug reappears.

7ddef19c introduces the bug but I don't know why

**Comment by black7375** [comment]
what you can do

1. use `!important`.
```css
  #toolbar-menubar {
    display: flex !important;
    flex-direction: row !important;
    justify-content: space-between !importnat;
  }
  #toolbar-menubar > spacer {
    order: 1000 !important; /* as Original's -moz-box-ordinal-group: 1000 */
    flex: 1 !important; /* Fill row */
  }
  #toolbar-menubar > .titlebar-buttonbox-container {
    order: 1000 !important; /* as Original's -moz-box-ordinal-group: 1000 */
  }
```

2. If not, you can find out which line is the cause by deleting each block and each line.
I've tried it on several computers and haven't been able to reproduce it, so this is the best for now.

3. Do you have any custom code?

**Comment by Jonas1312** [comment]
1) I tried with `!important` and it doesn't work
2) I actually think the vertical shift problem #207 and this problem #219 are the same bug, they just appear differently
3) I don't have any custom code

**Comment by Jonas1312** [comment]
#207 is caused by 6c7e0a54

**Comment by black7375** [comment]
Yes. It seems like a pretty complicated problem.

What comes to mind right now is specifying the flex for sure.
```css
    #toolbar-menubar > .titlebar-buttonbox-container {
      order: 1000 !important; /* as Original's -moz-box-ordinal-group: 1000 */
    }
```

=>
```css
    #toolbar-menubar > .titlebar-buttonbox-container {
      order: 1000 !important; /* as Original's -moz-box-ordinal-group: 1000 */
      flex-grow: 0 !important;
    }
```

I'll ask for help with Firefox CSS Reddit.
