### ISSUE TITLE
Photon-style changes to emulate old design

### ISSUE THREAD

**Issue by LoranRendel** [black7375/Firefox-UI-Fix#222]
This css-code will make Firefox look more like version 90.

```css
/* Remove gradient from menu separator */
.PanelUI-subView toolbarseparator.proton-zap {
    border-image: unset !important;
}

/* Remove color line from tab */
.tabbrowser-tab:is([selected], [multiselected]) .tab-context-line {
	--tab-line-color: transparent;
}

/* Fix menu paddings */
#appMenu-popup {
	--arrowpanel-border-radius: 0;
	--arrowpanel-menuitem-border-radius: 0;
	--arrowpanel-menuitem-padding: 5px 13px !important;
	--arrowpanel-menuitem-margin: 0 !important;
	--arrowpanel-menuimageblank-padding-horizontal: calc( var(--arrowpanel-menuicon-paddingx2) + 13px );
	--panel-separator-margin-horizontal: 0;
}

/* Full width separators */
.PanelUI-subView toolbarseparator{
	--panel-separator-margin: var(--panel-separator-margin-vertical) var(--panel-separator-margin-horizontal);
}

/* Menu back button padding */
.panel-header{
	padding: unset !important;
	padding-top: 4px !important;
}

/* Zoom menu item fix */
.toolbaritem-combined-buttons:not([widget-type="button-and-view"]){
	margin-inline-end: -5px; !important;
}
```
