### ISSUE TITLE
Decrease vertical padding(spacing) for drop-down list of combo box, if possible

### ISSUE THREAD

**Issue by alzhur** [black7375/Firefox-UI-Fix#227]
Subj.
Same way as it's already done for bookmarks, as example.
![combo box](https://user-images.githubusercontent.com/26850616/134545759-cb000ae9-ee3c-4c86-b52f-c7e733e89925.png)
Left side - Firefox 92 with Lepton, right side - Waterfox Classic (just for reference).

**Comment by black7375** [comment]
I'll try it in the next version.

For test: https://forum.nag.ru/

**Comment by black7375** [comment]
I thought it was a simple problem, but it doesn't seem possible.
![image](https://user-images.githubusercontent.com/25581533/136656379-2e1ed6da-eec3-43c4-8149-051f5e46a899.png)

```css
option {
  /* Can apply*/
  -moz-appearance: none;
  appearance: none;
  color: white !important;
  background: purple !important;
 
  /* Can't apply */
  padding-block: 0 !important;
  margin: 0 !important;
  min-block-size: 0 !important;
  line-height: 0 !important;
}
```

**Code with padding set**
https://github.com/mozilla/gecko-dev/blob/a373e254603253757afc75fc9e6e0a248cdb824f/layout/style/res/forms.css#L324-L342

**Similar Examples**
- https://stackoverflow.com/questions/17186777/is-there-any-way-to-add-padding-to-select-options-via-css
- https://stackoverflow.com/questions/22681141/select-option-padding-not-working-in-chrome
- https://stackoverflow.com/questions/11333488/css-form-height
