### ISSUE TITLE
How to modify internal settings FireFox pages styling

### ISSUE THREAD

**Issue by GlassGruber** [black7375/Firefox-UI-Fix#255]
Hei there! 
First of all thank you for this project, it works pretty well AFAICT on my Win7 machine!

**Is your feature request related to a problem?**

With FF ESR 91 I'm trying to find a way to style with light theming the internal settings pages. 

With FF ESR 78, using a dark theme (in my case [Arc Dark](https://addons.mozilla.org/en-US/firefox/addon/arc-dark-theme-we/) ) the internal settings pages where light colored as in screenshot below. 

I think that what I had was not considered the desired result, but it was for me! :P

![image](https://user-images.githubusercontent.com/1172428/138586885-635349ac-1f3b-42b9-8748-b6b699b01d70.png)

Now with ESR 91 this is the current full dark styling

![image](https://user-images.githubusercontent.com/1172428/138587188-08a8cf12-7cdc-43e5-9161-f47995d00dfa.png)

**The solution I'd like**

Is there anyway to style with `about:config` or `userChrome.css` the internal settings pages like in ESR 78? So that even with a dark theme, internal pages are styled like a light theme? 

**Alternatives I've considered**

I've tried with a naive approach, I've changed the `userChrome.css` file adding at bottom of file the rules as in the default light theme.
Unfortunately it looks like it's completely ignored, but as you can see in the previous picture, the Lepton style is correctly applied with icons, tab shape and all.

Here is what I've added without success (if I've made some dumb mistake please let me know!)

```css
@media (-moz-proton) {
  @media (-moz-prefers-color-scheme: dark) or (prefers-color-scheme: dark) {
    :host,
    :root {
      /* Keep these in sync with layout/base/PresShell.cpp, and plaintext.css */
      --in-content-page-background: #fff;
      --in-content-page-color: rgb(21, 20, 26);
      --in-content-text-color: var(--in-content-page-color);
      --in-content-deemphasized-text: rgb(91, 91, 102);
    }
  }
}
```

**Additional context**

I'm using the Original Lepton version, not Photon or Proton.

Thank you in advance for any suggestions!
