### ISSUE TITLE
Add styling of unloaded (inactive) tabs

### ISSUE THREAD

**Issue by ReporterX** [black7375/Firefox-UI-Fix#258]
**Is your feature request related to a problem?**
Yes, currently we can't recognize which tabs are unloaded (inactive) when using your CSS styling.

**The solution I'd like**
Add styling on the following:
Unloaded tabs
When hovering on unloaded tabs

**Comment by ReporterX** [comment]
It happens when you restore a session. Let's say you restore a session with 10 tabs in a window. Firefox won't load all tabs at once. Only the selected tab will be loaded (active). The rest are unloaded (inactive).

There are some addons which manage tab (un)loading. A tab will be unloaded if it is not selected and idle for some time, so as to release some memory.

Here are the CSS for loaded and unloaded tabs:
```
@media (-moz-proton)  {

    /* Loaded tabs */
    #tabbrowser-tabs .tabbrowser-tab:not([pending]) {

    }
    /* When hovering on loaded tabs */	
    #tabbrowser-tabs .tabbrowser-tab:not([pending]):hover {

    }
	
    /* Unloaded tabs */
    #tabbrowser-tabs .tabbrowser-tab[pending] {

    }
    /* When hovering on unloaded tabs */
    #tabbrowser-tabs .tabbrowser-tab[pending]:hover {

    }
  }	
```

**Comment by black7375** [comment]
Which one is better?

**Solution 1 - Circle content**

![image](https://user-images.githubusercontent.com/25581533/139621909-6184101e-f78f-4544-b66c-b986c7ca5f70.png)
```css
#tabbrowser-tabs .tabbrowser-tab[pending] .tab-text.tab-label::before {
  content: '•';
}
```

**Solution 2 - Itelic label**

![image](https://user-images.githubusercontent.com/25581533/139622008-94867b55-1885-4395-a440-329366bd43be.png)
```css
#tabbrowser-tabs .tabbrowser-tab[pending] .tab-text.tab-label {
  font-style: italic;
}
```
