### ISSUE TITLE
Menu entry in german translation cut off

### ISSUE THREAD

**Issue by terr72** [black7375/Firefox-UI-Fix#28]
**Describe the bug**
The menu entry "Neues privates Fenster" is shrinked to "Neues privates Fens...".
See the attached screenshot

**Expected behavior**
"Neues privates Fens..." should appear as "Neues privates Fenster"

**Environment (please complete the following information):**
 - Firefox Version: 89.0
 - OS:
   - [x] Linux
 - Theme:
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

![menu](https://user-images.githubusercontent.com/23163919/120462600-5fd3df00-c39b-11eb-8d72-f1e43278f578.png)

**Comment by SimYunSup** [comment]
![grafik](https://user-images.githubusercontent.com/47362439/120476937-21174680-c3e6-11eb-9c88-fb1c106a1fa7.png)
This bug works on Windows, too.

**Comment by black7375** [comment]
It seems to be a problem with the length.
Text truncation is also an issue that needs to be addressed, but it's not as serious a bug as a misaligned layout.

We need to check of Photon behavior later.
They are similar in size, so maybe there is a solution.

**Comment by SimYunSup** [comment]
This panel on Lepton should set wide width because of icon. So, It needs to modify width of the panel.
```css
  #appMenu-popup panelview {
    width: 30em !important; /* can modify panel width, original: 22.5em */
  }
```

**Comment by black7375** [comment]
It looks a bit wide in English.

**Before - After**
![image](https://user-images.githubusercontent.com/25581533/120492974-1212a300-c3aa-11eb-8d34-3547fbf7f9e1.png)
![image](https://user-images.githubusercontent.com/25581533/120492748-da0b6000-c3a9-11eb-8484-0bff5084ee24.png)

---

It's not that there isn't a way.
We can also set it up differently by language.
![image](https://user-images.githubusercontent.com/25581533/120493499-88170a00-c3aa-11eb-9364-a1be032cc664.png)

**Comment by terr72** [comment]
The german language string set by Firefox is _de_ only (checked for both Linux and Windows).
Also 23em is sufficient (at least for Linux, not tested with Windows).

```css
/* Sample Code */
:root[lang="de"] #appMenu-popup panelview {
  width: 23em !important; /* can modify panel width, original: 22.5em */
}
```

**Comment by SimYunSup** [comment]
Proton have translation cut off problem in another language too. So, I suggest `width: 25em` because I think it's reasonable in many language including English.
![image](https://user-images.githubusercontent.com/47362439/120541960-7fafe500-c425-11eb-852a-9a34be27de50.png)
```css
/* Panel View */
:root #appMenu-popup panelview {
  width: 25em !important; /* can modify panel width, original: 22.5em */
}
```
Can I make pull request of this?
