### ISSUE TITLE
Sidebar panel unreadable with some add-ons

### ISSUE THREAD

**Issue by kstev99** [black7375/Firefox-UI-Fix#283]
Some of the add-on generated sidebars are black text on black background and are unreadable.  History, Bookmarks, Ublock all look OK but examples: Update Scanner, Containers Sync, Snooze (Snoozed Tabs) all are unreadable.  Not sure if there is a fix all solution or if each extension would have to be addressed individually

![2021-11-28_114818](https://user-images.githubusercontent.com/32485060/143940215-617ce869-4151-4a59-830e-9d325d237bde.jpg)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 94.02
 - OS:
   - [ ] Linux
   - [X] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [X] Dark (blackredtheme)
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
   - [ ] 
     

**Additional context**
My additions to userchrome.css

```css
.browserContainer > findbar {
  -moz-box-ordinal-group: 0;
  position: fixed !important;
  right: 1em;
  border: 1px solid threedshadow !important;

  /* Hide the "border" at the top by removing the box-shadow and background-image */
  border-top: none !important;
  box-shadow: none !important;
  background-image: none !important;

  /* Uncomment to add a transition from the top */
  /*
  transition: 400ms !important;
  z-index: 0 !important;
  */
}
.findbar-closebutton {
  margin-inline-start: 0.5em !important;
  vertical-align: middle !important;
  margin-bottom: 0.25em !important;
  height: inherit !important;
}
/* Bookmarks Sidebar change HOVER Color
*/
/* Bookmarks sidebar: change hover color */
#bookmarks-view treechildren::-moz-tree-cell(hover) { background-color: #102257 !important }
/* 6F4B4B  ROSE / 585858 GRAY */
/* Bookmarks Sidebar - Dark Red background color for selected bookmark */
#bookmarks-view treechildren::-moz-tree-row(selected) {
  background-color: #610000   !important;
}
/* #6F4B4B BrightBlue / #610000 DKRED */
#bookmarksPanel treechildren:-moz-tree-cell-text(selected)
{
background-color: #610000   !important;
color: white !important;
font-weight: Bold !important;
/* font-size: 12px !important; */

}
/*CHANGE SCROLLBAR COLOR ON SIDE PANEL */
/*.panel-subview-body{
  scrollbar-face-color: rgb(94, 94, 94);
  scrollbar-track-color: rgb(57, 59, 65);
  scrollbar-color: rgb(18,18,108) rgb(0,0,48);
  scrollbar-width: auto;
 } */
 #permList, scrollbar{
  scrollbar-face-color: rgb(97, 0, 0);
  scrollbar-track-color: rgb(72, 10, 10);
  scrollbar-color: rgb(97, 0, 0) rgb(18,13,13);
  scrollbar-width: auto;
 }
 
 /* SELECTED TAB ADDITIONAL BORDER or ZEROPX for NONE*/
 .tabbrowser-tab:is([selected="true"]) > .tab-stack > .tab-background {
  border: 0px solid rgb(97, 0, 0) !important;
}

/* CHANGE STAR BOOKMARK */	
#star-button[starred] {
	fill-opacity: 1;
	fill: #C30052!important;
}

/*** Sidebar Text Color / Font Size Formatting ***/
/* 14px black text */
.sidebar-placesTree treechildren::-moz-tree-cell-text {
  font-size: 12px !important;
  color: rgb(255, 255, 255) !important;
}

/* OUTLINE INACTIVE TABS SLIGHTLY */
/* .tabbrowser-tab:not([selected="true"]) > .tab-stack > .tab-background {
  border: 2px solid rgba(130, 130, 130, 0.3) !important;
} */

/* Selected Tab Background Dark Blue */
.tab-background[selected="true"] {
      background-color: #030355 !important;
      background-image: none !important;
    }
    
    /* Change Selected text color in URL Bar */
    #urlbar-input::selection{
  background-color: #610000 !important;
}
/* Tab: hovered color NOT Selected */
#tabbrowser-tabs .tabbrowser-tab:hover:not([selected]) .tab-content {
  background-color: #2E0817 !important;
  border: 2px solid rgb(97, 0, 0) !important;
}

/* Remove SHARE from context menu */
#tabContextMenu .share-tab-url-item {
    display: none
}

.tab-close-button:hover {background-color: #8B0101 !important;}

/* Put Border around drop down bookmarks menus */
#PlacesToolbarItems > .bookmark-item > menupopup{
  --panel-border-color: rgb(97, 0, 0) !important;
  --menuitem-hover-background-color: rgb(97, 0, 0) !important;
}
.menupopup-arrowscrollbox{
  border: 3px solid var(--panel-border-color) !important;
}

/*bookmarks toolbar Change Background and Hover Color*/
#PlacesToolbar menupopup[placespopup="true"] {
  --arrowpanel-background: #030315 !important;
  --arrowpanel-color: white !important;
}
/* Change Highlighted Main Toolbar Icon Color and Hover */
:root{
  --toolbarbutton-active-background: #610000 !important;
  --toolbarbutton-hover-background: #610000 !important;
}
/* CHANGE Highlight color in dropdown bookmarks and Hamburger menu */
#appMenu-popup toolbarbutton.subviewbutton:not([disabled], [open],  :active):is(:hover) {
background-color: #610000 !important; 
}
menupopup {
--panel-item-hover-bgcolor: #610000 !important;
--panel-item-active-bgcolor: #0B3656 !important;
}
```
