### ISSUE TITLE
Disable smooth transitions for sidebar

### ISSUE THREAD

**Issue by jamesWalker55** [black7375/Firefox-UI-Fix#284]
**Is your feature request related to a problem?**
Currently, CSS transitions are applied to the sidebar when activating and disactivating the sidebar. However, most pages have variable content depending on the width of the browser.

Firefox normally compensates for this with **scroll anchoring**, by aligning the view to the first visible element. However, the smooth transition disables this anchoring as it causes the browser to repeatedly adjust the view. You can see an error like this in the console:

![image](https://user-images.githubusercontent.com/30405220/144679875-0dbe4b04-2840-47fe-a557-75ab93a8d79f.png)

[From this recording, you can also see that the view is no longer anchored to any element when smooth transitions is enabled.](https://streamable.com/owutqv) This makes it very difficult to keep track of your position in the page.

https://user-images.githubusercontent.com/25581533/144735912-563270c0-d980-4fef-b4a8-b46c99394ad7.mp4

In order to enable scroll anchoring, I would like to disable smooth transitions for the sidebar.

I also personally think that the smooth transition is distracting. When deactivating the sidebar, the sidebar does not collapse completely, then suddenly disappears, causing the page to "jump" visually. See the recording.

**The solution I'd like**
I would like to suggest disabling smooth transitions for the sidebar.

**Additional context**
Disabling transitions can be done by commenting out a few lines of code in `userChrome.css`:

```css
    /*- Sidebar --------------------------------------------------------------*/
    #sidebar-box {
      /* like #sidebar-box > #sidebar */
      min-width: 14em;
      width: 18em;
      max-width: 36em;

      /* Animation */
      /*transition: margin-inline-start 0.25s var(--animation-easing-function), opacity 0.25s ease-in-out,
        visibility 0s linear !important;*/  /* comment this out */
    }
    #sidebar-box[hidden="true"] {
      display: -moz-box !important;
      margin-inline-start: -18em;
      opacity: 0;
      visibility: collapse;
      /*transition-delay: 0s, 0s, 0.25s !important;*/  /* comment this out */
    }
```
