### ISSUE TITLE
min/max/close buttons changed

### ISSUE THREAD

**Issue by leadweedy** [black7375/Firefox-UI-Fix#290]
**Is your feature request related to a problem?**

A change is implemented in Firefox 96 where when the tabs are in the titlebar (i.e. titlebar option is *unchecked* in the customize page) and the light/dark/alpenglow themes are enabled, the min/max/close buttons are replaced from the system ones with firefox provided ones. At least, this is the behavior in linux. I havent verified this on other platforms.

**The solution I'd like**

The default system buttons should be used for consistency. 

**Additional context**

default buttons with light/dark/alpenglow theme in FF96: ![mozilla buttons](https://raw.githubusercontent.com/leadweedy/Firefox-Proton-Square/main/images/mozilla_buttons.png)

default KDE breeze buttons: ![breeze buttons](https://raw.githubusercontent.com/leadweedy/Firefox-Proton-Square/main/images/breeze_buttons.png)

It can can be reverted with the following code in `userChrome.css`

```
.titlebar-button {
  appearance: auto !important;
}
.titlebar-min:-moz-lwtheme, .titlebar-max:-moz-lwtheme, .titlebar-restore:-moz-lwtheme, .titlebar-close:-moz-lwtheme {
  list-style-image: none !important;
}
```

**Comment by leadweedy** [comment]
additional note: this is only relevant for linux. on windows it causes the window controls to disappear, so it should be behind a pref or disabled by default

**Comment by black7375** [comment]
Has confirmed.

For memo.
This is the code that is causing the problem.
```css
  .titlebar-button:-moz-lwtheme {
    appearance: none;
    border-radius: 100%;
  }
  .titlebar-button > .toolbarbutton-icon:-moz-lwtheme {
    padding: 6px;
    -moz-context-properties: stroke;
    stroke: currentColor;
  }
  .titlebar-min:-moz-lwtheme {
    list-style-image: url(chrome://browser/skin/window-controls/minimize.svg);
  }
  .titlebar-max:-moz-lwtheme {
    list-style-image: url(chrome://browser/skin/window-controls/maximize.svg);
  }
  .titlebar-restore:-moz-lwtheme {
    list-style-image: url(chrome://browser/skin/window-controls/restore.svg);
  }
  .titlebar-close:-moz-lwtheme {
    list-style-image: url(chrome://browser/skin/window-controls/close.svg);
  }
  .titlebar-button:-moz-lwtheme:hover {
    background-color: color-mix(in srgb, currentColor 12%, transparent);
  }
  .titlebar-button:-moz-lwtheme:hover:active {
    background-color: color-mix(in srgb, currentColor 20%, transparent);
  }
  .titlebar-close:-moz-lwtheme:hover {
    background-color: #d70022;
    color: white;
  }
  .titlebar-close:-moz-lwtheme:hover:active {
    background-color: #ff0039;
  }
```

Putting this code in solves the problem.
```css
.titlebar-button:-moz-lwtheme {
  appearance: auto !important;
}
.titlebar-min:-moz-lwtheme, .titlebar-max:-moz-lwtheme, .titlebar-restore:-moz-lwtheme, .titlebar-close:-moz-lwtheme {
  list-style-image: none !important;
}
.titlebar-button:-moz-lwtheme:hover,
.titlebar-button:-moz-lwtheme:hover:active {
  background-color: unset !important;
  color: unset !important;
}
```
