### ISSUE TITLE
Loss of smooth animation for Tree Style Tabs auto-hide/show with release v4.5.6

### ISSUE THREAD

**Issue by Koraydi** [black7375/Firefox-UI-Fix#305]
**Describe the bug**
Upon updating to release v4.5.6 and adding the TSS css code Auto-show/hide sidebar by mouseover (hover), there is no longer a smooth animation.

https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover

**Expected behavior**
A smooth open and close animation when moused over

**Screenshots**
 Lack of smooth animation with release v4.5.6 

https://user-images.githubusercontent.com/91707942/148685887-db260fb0-9d57-4c3e-80bf-4ae39f2809ed.mp4

Smooth animation with a previous release (I dont remember the release as it was so long ago and I went to update today because parts of it had started to break with Firefox updates)

https://user-images.githubusercontent.com/91707942/148685931-fab2c9de-5423-442f-8c27-a54da04bb0fb.mp4

**Environment:
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
All I ever did was add the code from the TSS Wiki to the userChrome provided in the release.

**Comment by black7375** [comment]
Try to this code

```css
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] {
  overflow: hidden;
  min-width: 40px;
  max-width: 40px;
  transition: margin-inline-start 0.25s var(--animation-easing-function), opacity 0.25s ease-in-out,
      visibility 0s linear, min-width 0.25s var(--animation-easing-function), max-width 0.25s var(--animation-easing-function) !important;
  border-right: 1px solid #0c0c0d;
  z-index: 2;
}

/*Expand to 260px on hover*/
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover,
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar {
  min-width: 260px !important;
  max-width: 260px !important;
  z-index: 1;
}
```
