### ISSUE TITLE
Disappeared border around active tab with v4.5.7

### ISSUE THREAD

**Issue by roland-rollo** [black7375/Firefox-UI-Fix#321]
**Describe the bug**

With version 4.5.7 Lepton disappear border around active tab.
**Expected behavior**

How to restore it.
**Screenshots**

![old](https://user-images.githubusercontent.com/44477799/150605399-05efae48-47c3-43bd-89b9-8b1916778344.png)
![ps_20220122155501](https://user-images.githubusercontent.com/44477799/150643593-6248670d-b9bf-482f-bc4a-2441f9f5f0ce.png)

**Environment:**

 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [X] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [X] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))
Edited Dark theme changed to black color as background. It's especially annoying, as I use compact mode. 

**Additional context**

**Comment by black7375** [comment]
Hello, what's your theme?

**Comment by roland-rollo** [comment]
Using Firefox Color addon, I edited Dark theme. I use compact mode, but in "normal" or biggest it's the same.

![ps_20211227100224](https://user-images.githubusercontent.com/44477799/150695779-75fb112d-4fa7-4051-a42e-b4a8e8c3f3e9.png)
![ps_20211227100228](https://user-images.githubusercontent.com/44477799/150695781-4bfcb10b-9249-4521-a191-07ba928608c5.png)
![ps_20211227100233](https://user-images.githubusercontent.com/44477799/150695782-4f7174a6-426f-461a-93dc-a238de1b235d.png)
![ps_20211227100238](https://user-images.githubusercontent.com/44477799/150695784-a3905d0e-a588-4a70-88d2-c74c3692f7fa.png)

**Comment by black7375** [comment]
The next code in Firefox:
```css
:root:not([lwtheme-mozlightdark]) #TabsToolbar:not([brighttext]) #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected="true"], [multiselected]) > .tab-stack > .tab-background:-moz-lwtheme {
    box-shadow: 0 0 0 1px var(--tab-line-color, var(--tabs-border-color, rgba(128,128,142,0.9))), 0 0 4px rgba(128,128,142,0.5);
}

#TabsToolbar:not([brighttext]) #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected="true"], [multiselected]) > .tab-stack > .tab-background {
    box-shadow: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9)), 0 0 4px rgba(128,128,142,0.5);
}
```
It was changed like this.
```css
#tabbrowser-tabs:not([noshadowfortests]) .tab-background:is([selected], [multiselected]) {
  box-shadow: 0 0 4px rgba(0,0,0,.4);
}
```
