### ISSUE TITLE
[Question] How to change colours of tab bar and nav bar?

### ISSUE THREAD

**Issue by pranau97** [black7375/Firefox-UI-Fix#323]
I am running Firefox on macOS along with Tree Style Tabs and I've hidden the tab bar entirely using the below addition to your CSS:

```CSS
.tabbrowser-tab {
  visibility: collapse !important;
}

#nav-bar {
  margin-top: -34px;
  margin-left: 75px;
  box-shadow: none !important;
}

#TabsToolbar {
  height: 34px !important;
}
```

This is the result:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12474765/150836155-f6890f73-ec57-486b-a191-1fd234626dfd.png">

As you can see, the tab bar (area behind the close, maximize, minimize buttons) and nav bar have different background colours. Is there a way to set them both to the same colour? Any help/resources to change this would be appreciated. Thanks!

**Comment by black7375** [comment]
After editing one line(https://github.com/black7375/Firefox-UI-Fix/commit/20171b99845b00cc1d36c52ff4d6b4f2b5fb1383), insert the following code

![image](https://user-images.githubusercontent.com/25581533/150920011-b17b548e-4667-43c7-b89e-c1c2d8277f70.png)

```css
#navigator-toolbox {
  --lwt-accent-color: var(--toolbar-bgcolor);
  --mac-bgcolor: var(--toolbar-bgcolor);
}
```

The colors will be unified while considering the compatibility between Firefox versions and themes.
(But, Not all OS compatibility has been considered yet.)
