### ISSUE TITLE
[Discussion] Video Player Design

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#335]
Hello, the next version is planning to add 1 to 2 features, and one of them is a video design.

**Original**

As you can see, it looks stuffy.

![image](https://user-images.githubusercontent.com/25581533/154871494-c0f082f6-c40b-41bd-848b-4f908e4652f2.png)

**One Line Concept**

I changed the background to look transparent.

![image](https://user-images.githubusercontent.com/25581533/154871502-e2ea01df-92a4-48ff-95c1-901bfeeefa2d.png)

**Two Line Concept**

I adjusted it to two lines like YouTube.

![image](https://user-images.githubusercontent.com/25581533/154871507-a8f0801e-677b-4b81-a295-6f122b4ba7f8.png)

---

Which one do you prefer?
Please express it with an emoji.

- Original: :confused: 
- One Line Concept: :heart:
- Two Line Concept: :rocket: 

The comments are good, too.

**Comment by black7375** [comment]
Thank you all. Then I'll work based on the second style.

PS. Try the following code to get the third style.
```css
/* Second Line */
#controlsContainer .controlBar {
  flex-wrap: wrap;
  justify-content: space-between;
  align-content: space-around;
  height: calc(var(--controlBar-height) + var(--thumb-size)) !important;
  padding-inline: 0 !important; /* Original: 9px */
}
#controlsContainer .scrubberStack {
  /* Vertical */
  order: -1;
  height: var(--thumb-size) !important;
  transform: translateY(calc(var(--thumb-size) / 2));

  /* Horizontal */
  flex-basis: auto !important;
  width: 100%;
  margin-inline: 0 !important;
}
#controlsContainer .positionDurationBox {
  flex-grow: 2;
  margin-left: 15px !important;
  text-align: left !important;
}
#playButton {
  margin-left: 9px !important;
}
#fullscreenButton {
  margin-right: 9px !important;
}
#controlsContainer .duration {
  color: #dadada !important; # /* Original: #929292 */
}
```
