### ISSUE TITLE
Shadow under selected pinned tab on MacOS

### ISSUE THREAD

**Issue by osovitskiy** [black7375/Firefox-UI-Fix#342]
**Describe the bug**
After upgrading to 4.6.0 shadow appears under selected pinned tab

**Screenshots**
<img width="195" alt="Screenshot 2022-03-06 at 23 57 35" src="https://user-images.githubusercontent.com/4147169/156948078-926d0ef5-688a-4d51-99f9-5dc1d4aaa4d3.png">

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 97.0.2
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Does adding the following code to `userChrome.css` solve the problem?

```css
/* Pinned Tab - tabbrowser-arrowscrollbox overflowing */
#tabbrowser-tabs[positionpinnedtabs] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[pinned] {
  z-index: 0 !important;
}
```
