### ISSUE TITLE
Top window border is missing with Firefox 91.8.0esr

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#358]
**Describe the bug**

I’m using Firefox 91.8.0esr with Firefox-UI-Fix (former Lepton) on Windows 10 and just realized that the top black border of my Firefox window is missing. This only applies to FF and not to the FF about pop up window (see second pictures please). How do I get it back OR remove all the remaining black borders of the Firefox window? Any help is really appreciated!

**Expected behavior**

Top border should displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/25581533/163081557-c134e1a1-8a84-487d-91ee-a511ace45b02.png)
![image](https://user-images.githubusercontent.com/25581533/163081567-3ec4f0c3-9a42-4104-b328-80f473e39929.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows: 10
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

https://www.reddit.com/r/FirefoxCSS/comments/u17o1p/top_black_window_border_is_missing_with_firefox/

**Comment by black7375** [comment]
It's a upstream compatibility  issue.

![Win10-2022-04-12-21-11-25](https://user-images.githubusercontent.com/25581533/163081772-51f1c4b4-22a6-478b-81d7-81796f402546.png)
![Win10-2022-04-12-21-11-33](https://user-images.githubusercontent.com/25581533/163081779-08f35ed1-bf4c-48e8-b1fe-545fd8b371f3.png)

https://searchfox.org/mozilla-esr91/source/browser/themes/windows/compacttheme.css#93
```css
/* Restored windows get an artificial border on windows, because the lwtheme background
 * overlaps the regular window border. That isn't the case for us, so we avoid painting
 * over the native border with our custom borders: */
#navigator-toolbox {
  /* These are !important to avoid specificity-wars with the selectors that add borders here. */
  background-image: none !important;
  border-top: none !important; /* <- This code */
  box-shadow: none !important;
  padding-top: 0 !important;
}
```
