### ISSUE TITLE
Tabs + window controls not displayed with v5 default settings

### ISSUE THREAD

**Issue by kaylynn234** [black7375/Firefox-UI-Fix#368]
**Describe the bug**
I think this is probably pretty self-explanatory, but if you don't enable `userChrome.tab.on_bottom` you.. just won't
have tabs or window controls at all. Needless to say that makes navigation a bit difficult:
![An image depicting a rather headless Firefox instance](https://kaylynn.might-be.gay/EjkfKFCpmN4yrg.png)

And no. This image is not cropped.

I did some hunting in `leptonChrome.css` and seem to have found the culprit. Applying the following CSS
**unconditionally** (i.e, not within a media query) appears to *mostly* fix the issue:
```css
#titlebar {
  -moz-appearance: none !important;
}
```

There were a few other weird tweaks i had to make, and for the sake of completeness I'll leave them here if it's helpful
in providing a solution:

<details>
<summary>Expand codeblock</summary>

```css
#navigator-toolbox {
  display: flex !important;
  flex-wrap: wrap;
}

#titlebar,
#nav-bar,
#PersonalToolbar,
#tab-notification-deck,
#tab-notification-deck-template {
  flex-basis: 100%;
}

#titlebar {
  order: 0;
  -moz-appearance: none !important;
  --tabs-navbar-shadow-size: 0px;
}

#tab-notification-deck {
  order: 1;
}

#PersonalToolbar {
  order: 2;
}

#navigator-toolbox {
  padding-top: var(--uc-titlebar-padding) !important;
}

:root:not([sizemode="maximized"]) {
  --uc-titlebar-padding: 0px;
}

:root[sizemode="maximized"] {
  --uc-titlebar-padding: 8px;
}
```

</details>

**I'm not sure how many of these changes are necessary**. I used the existing CSS and good ol' trial and error until
Firefox behaved. I opened an issue instead of a PR since I... honestly have no idea what I'm doing. This is my first
time interacting with Lepton or Firefox in this way, so I figure somebody else will have a better solution to this.

I really appreciate the project and couldn't live without it. Thanks for your hard work!

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 99.0.1 (Build ID `20220411174855`)
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))
