### ISSUE TITLE
Cusomizable autohide timeout and animation speed

### ISSUE THREAD

**Issue by chermnyx** [black7375/Firefox-UI-Fix#462]
**Is your feature request related to a problem?**

Currently when a user moves cursor away from element with autohide on the element are still shown for some time, which is not customizable. 
The animations may be too short or too long for some users (some of them may want to disable the animations completely)

**The solution I'd like**

Add options to customize the delay before hiding and animation speed 
Add option to turn off the animation

**Comment by black7375** [comment]
It is not a stabilized API, but if you put the next code into `userChrome.css`, you can customize it.

```css
:root {
  --uc-autohide-toolbar-speed: 0.25s;
  --uc-autohide-toolbar-delay: 600ms;
}
```

---

When you using installation script, use the override file.
https://github.com/black7375/Firefox-UI-Fix/wiki/Options#using-scripts

**Comment by chermnyx** [comment]
Does it support sidebar?

**Comment by black7375** [comment]
Now, you can customize like this.

```css
#sidebar-box {
  --uc-autohide-sidebar-speed: 750ms;
  --uc-autohide-fullscreen-sidebar-speed: 1s;
  --uc-autohide-sidebar-delay: 600ms;
}
```
