### ISSUE TITLE
Remove muted icon when not playing sound

### ISSUE THREAD

**Issue by JohnyP36** [black7375/Firefox-UI-Fix#486]
**Is your feature request related to a problem?**

No

**The solution I'd like**

The Firefox normal/standard is that regardless if there is sound playing on a page or not it will show the muted icon. 

**Screenshots or video**

 See the most left tab
<details> 

![afbeelding](https://user-images.githubusercontent.com/81161435/196909523-0739fc3d-9a62-4cd4-a4ce-926e76c144be.png)

</details

**Alternatives I've considered**

I would like that the muted icon is not shown/visible if there is no sound/video playing in that browser tab. 

So, only when you muted the tab and there is a video playing the muted icon must be shown. Otherwise not.

**Additional context**

**Comment by black7375** [comment]
One click unmute is a pretty natural motion, so I will keep it as a default.
It is not right now, but it is likely to be added as an option with #478 later

**Comment by JohnyP36** [comment]
As until now, you did not include it as an option and I got not create a work-around for this problem. 
Do you know how I could do this?

**Comment by black7375** [comment]
I'm sorry. I thought I answered, but I just thought about it and didn't comment.

---

I checked it, but there is a difficulty in implementation.
Firefox treats everything as the same mute, whether sound plays on the page or not.
The `soundplaying` is not known until you set `unmute`.

As a possible trick, the tab that once executed the sound can be seen by injecting style `--soundplaying-removal-delay: 2700ms;`.
However, it remains permanently until the tab is closed, so it is not good for user experience.
```css
.tabbrowser-tab[muted="true"]:not([style*="--soundplaying-removal-delay: 2700ms;"]) .tab-icon-overlay:not([sharing], [crashed])[muted] {
  opacity: 0 !important;
}
```

**Comment by JohnyP36** [comment]
As soon as I tested it I will close this issue.

**Comment by black7375** [comment]
Switching to webextension might give you a way to check playing sound.
- https://github.com/black7375/Firefox-UI-Fix/discussions/502

I think it will be slower to implement it because it has been busy recently, but I will review it again if it is possible to implement it when I switch. (You don't have to close the issue)

**Comment by JohnyP36** [comment]
```css
.tabbrowser-tab[muted="true"]:not([style*="--soundplaying-removal-delay: 2700ms;"]) .tab-icon-overlay:not([sharing], [crashed])[muted] {
  opacity: 0 !important;
}
```
Doesn't do the job, as `--soundplaying-removal-delay: 2700ms` is permanent (it stays there whether sound is playing or not).
So, you are right: Firefox doesn't offer us/me to have separate rules for "sound playing but muted" and "muted and not playing sound".
