### ISSUE TITLE
Can't Access Top of Page with Top_Tab_Bar_hidden and autohide Nav_bar and Bookmark_bar

### ISSUE THREAD

**Issue by PhoenixCODE2322** [black7375/Firefox-UI-Fix#503]
**Describe the bug**
A little bit area of Top is not accessible. i have some buttons on Top there and when my mouse goes there, Nav_bar Opens up.

**Expected behavior**
Able to access Top portion of Screen with autohide feature enabled.

**Screenshots**
![firefox_x9aEehcsUe](https://user-images.githubusercontent.com/75798544/200240939-dbb07278-cc40-4a70-8298-c173c60d2106.gif)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  106.0.5 (64-bit)
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// ** Theme Default Options ****************************************************
// userchrome.css usercontent.css activate
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// Proton Enabled #127 || Removed at 97 #328 (Maintained for compatibility with ESR)
user_pref("browser.proton.enabled", true);

// Proton Tooltip
user_pref("browser.proton.places-tooltip.enabled", true);

// Fill SVG Color
user_pref("svg.context-properties.content.enabled", true);

// CSS Color Mix - 88 Above
user_pref("layout.css.color-mix.enabled", true);

// CSS Blur Filter - 88 Above
user_pref("layout.css.backdrop-filter.enabled", true);

// Restore Compact Mode - 89 Above
user_pref("browser.compactmode.show", true);

// about:home Search Bar - 89 Above
user_pref("browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar", false);

// CSS's `:has()` selector #457 - 103 Above
user_pref("layout.css.has-selector.enabled", true);

// Browser Theme Based Scheme - Will be activate 95 Above
// user_pref("layout.css.prefers-color-scheme.content-override", 3);

// ** Theme Related Options ****************************************************
// == Theme Distribution Settings ==============================================
// The rows that are located continuously must be changed `true`/`false` explicitly because there is a collision.
// https://github.com/black7375/Firefox-UI-Fix/wiki/Options#important
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",        true); // Original
user_pref("userChrome.tab.photon_like_padding",       false); // Photon

user_pref("userChrome.tab.dynamic_separator",          true); // Original, Proton
user_pref("userChrome.tab.static_separator",          false); // Photon
user_pref("userChrome.tab.static_separator.selected_accent", false); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",     true); // Original
user_pref("userChrome.tab.newtab_button_smaller",     false); // Photon
user_pref("userChrome.tab.newtab_button_proton",      false); // Proton

user_pref("userChrome.icon.panel_full",                true); // Original, Proton
user_pref("userChrome.icon.panel_photon",             false); // Photon
user_pref("userChrome.icon.panel_sparse",             false); // Just option

// Original Only
user_pref("userChrome.tab.box_shadow",                 true);
user_pref("userChrome.tab.bottom_rounded_corner",      true);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",   false);
user_pref("userChrome.rounding.square_tab",           false);

// == Theme Compatibility Settings =============================================
// user_pref("userChrome.compatibility.accent_color",         true); // Firefox v103 Below
// user_pref("userChrome.compatibility.covered_header_image", true);
// user_pref("userChrome.compatibility.panel_cutoff",         true);
// user_pref("userChrome.compatibility.navbar_top_border",    true);
// user_pref("userChrome.compatibility.dynamic_separator",    true); // Need dynamic_separator

// user_pref("userChrome.compatibility.os.linux_non_native_titlebar_button", true);
// user_pref("userChrome.compatibility.os.windows_maximized", true);

// == Theme Custom Settings ====================================================
// -- User Chrome --------------------------------------------------------------
// user_pref("userChrome.theme.proton_color.dark_blue_accent", true);
user_pref("userChrome.theme.monospace",                     true);

// user_pref("userChrome.decoration.disable_panel_animate",    true);
// user_pref("userChrome.decoration.disable_sidebar_animate",  true);

// user_pref("userChrome.autohide.tab",                        true);
// user_pref("userChrome.autohide.tab.opacity",                true);
// user_pref("userChrome.autohide.tab.blur",                   true);
// user_pref("userChrome.autohide.tabbar",                     false);
user_pref("userChrome.autohide.navbar",                     true);
user_pref("userChrome.autohide.bookmarkbar",                true);
user_pref("userChrome.autohide.sidebar",                    false);
// user_pref("userChrome.autohide.fill_urlbar",                true);
// user_pref("userChrome.autohide.back_button",                true);
// user_pref("userChrome.autohide.forward_button",             true);
// user_pref("userChrome.autohide.page_action",                false);
user_pref("userChrome.autohide.toolbar_overlap",            false);
user_pref("userChrome.autohide.toolbar_overlap.allow_layout_shift", false);

// user_pref("userChrome.hidden.tab_icon",                     true);
// user_pref("userChrome.hidden.tab_icon.always",              true);
user_pref("userChrome.hidden.tabbar",                       true);
// user_pref("userChrome.hidden.navbar",                       true);
user_pref("userChrome.hidden.sidebar_header",               false);
user_pref("userChrome.hidden.sidebar_header.vertical_tab_only", false);
user_pref("userChrome.hidden.urlbar_iconbox",               true);
// user_pref("userChrome.hidden.bookmarkbar_icon",             true);
// user_pref("userChrome.hidden.bookmarkbar_label",            true);
user_pref("userChrome.hidden.disabled_menu",                true);

// user_pref("userChrome.centered.tab",                        true);
// user_pref("userChrome.centered.tab.label",                  true);
user_pref("userChrome.centered.urlbar",                     true);
// user_pref("userChrome.centered.bookmarkbar",                false);

// user_pref("userChrome.rounding.square_button",              true);
// user_pref("userChrome.rounding.square_panel",               true);
// user_pref("userChrome.rounding.square_panelitem",           true);
// user_pref("userChrome.rounding.square_menupopup",           true);
// user_pref("userChrome.rounding.square_menuitem",            true);
// user_pref("userChrome.rounding.square_field",               true);
// user_pref("userChrome.rounding.square_checklabel",          true);

// user_pref("userChrome.padding.first_tab",                   true);
// user_pref("userChrome.padding.first_tab.always",            true);
// user_pref("userChrome.padding.drag_space",                  true);
// user_pref("userChrome.padding.drag_space.maximized",        true);

// user_pref("userChrome.padding.menu_compact",                true);
// user_pref("userChrome.padding.bookmark_menu.compact",       true);
// user_pref("userChrome.padding.urlView_expanding",           true);
// user_pref("userChrome.padding.urlView_result",              true);
// user_pref("userChrome.padding.panel_header",                true);

// user_pref("userChrome.urlView.move_icon_to_left",           true);
// user_pref("userChrome.urlView.go_button_when_typing",       true);
// user_pref("userChrome.urlView.always_show_page_actions",    true);

// user_pref("userChrome.tabbar.as_titlebar",                  true);
user_pref("userChrome.tabbar.on_bottom",                    false);
// user_pref("userChrome.tabbar.on_bottom.above_bookmark",     true); // Need on_bottom
user_pref("userChrome.tabbar.on_bottom.menubar_on_top",     false); // Need on_bottom
// user_pref("userChrome.tabbar.on_bottom.hidden_single_tab",  true); // Need on_bottom
user_pref("userChrome.tabbar.one_liner",                    false);
user_pref("userChrome.tabbar.one_liner.combine_navbar",     false); // Need one_liner
// user_pref("userChrome.tabbar.one_liner.tabbar_first",       true); // Need one_liner
// user_pref("userChrome.tabbar.one_liner.responsive",         true); // Need one_liner

// user_pref("userChrome.tab.always_show_tab_icon",            true);
// user_pref("userChrome.tab.close_button_at_pinned",          true);
// user_pref("userChrome.tab.close_button_at_pinned.always",   true);
// user_pref("userChrome.tab.close_button_at_pinned.background", true);
// user_pref("userChrome.tab.close_button_at_hover.always",    true); // Need close_button_at_hover
user_pref("userChrome.tab.sound_show_label",                true); // Need remove sound_hide_label

// user_pref("userChrome.panel.remove_strip",                  true);
// user_pref("userChrome.panel.full_width_separator",          true);
// user_pref("userChrome.panel.full_width_padding",            true);

user_pref("userChrome.sidebar.overlap",                     false);

// user_pref("userChrome.icon.disabled",                       true);
// user_pref("userChrome.icon.account_image_to_right",         true);
// user_pref("userChrome.icon.account_label_to_right",         true);
// user_pref("userChrome.icon.menu.full",                      true);
// user_pref("userChrome.icon.global_menu.mac",                true);

// -- User Content -------------------------------------------------------------
// user_pref("userContent.player.ui.twoline",                  true);

// user_pref("userContent.page.proton_color.dark_blue_accent", true);
// user_pref("userContent.page.proton_color.system_accent",    true);
user_pref("userContent.page.monospace",                     true);

// == Theme Default Settings ===================================================
// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.compatibility.theme",       true);
user_pref("userChrome.compatibility.os",          true);

user_pref("userChrome.theme.built_in_contrast",   true);
user_pref("userChrome.theme.system_default",      true);
user_pref("userChrome.theme.proton_color",        true);
user_pref("userChrome.theme.proton_chrome",       true); // Need proton_color
user_pref("userChrome.theme.fully_color",         true); // Need proton_color
user_pref("userChrome.theme.fully_dark",          true); // Need proton_color

user_pref("userChrome.decoration.cursor",         true);
user_pref("userChrome.decoration.field_border",   false);
user_pref("userChrome.decoration.download_panel", true);
user_pref("userChrome.decoration.animate",        true);

user_pref("userChrome.padding.tabbar_width",      true);
user_pref("userChrome.padding.tabbar_height",     true);
user_pref("userChrome.padding.toolbar_button",    true);
user_pref("userChrome.padding.navbar_width",      true);
user_pref("userChrome.padding.urlbar",            true);
user_pref("userChrome.padding.bookmarkbar",       true);
user_pref("userChrome.padding.infobar",           true);
user_pref("userChrome.padding.menu",              true);
user_pref("userChrome.padding.bookmark_menu",     true);
user_pref("userChrome.padding.global_menubar",    true);
user_pref("userChrome.padding.panel",             true);
user_pref("userChrome.padding.popup_panel",       true);

user_pref("userChrome.tab.multi_selected",        true);
user_pref("userChrome.tab.unloaded",              true);
user_pref("userChrome.tab.letters_cleary",        true);
user_pref("userChrome.tab.close_button_at_hover", true);
user_pref("userChrome.tab.sound_hide_label",      true);
user_pref("userChrome.tab.sound_with_favicons",   true);
user_pref("userChrome.tab.pip",                   true);
user_pref("userChrome.tab.container",             true);
user_pref("userChrome.tab.crashed",               true);

user_pref("userChrome.fullscreen.overlap",        true);
user_pref("userChrome.fullscreen.show_bookmarkbar", true);

user_pref("userChrome.icon.library",              true);
user_pref("userChrome.icon.panel",                true);
user_pref("userChrome.icon.menu",                 true);
user_pref("userChrome.icon.context_menu",         true);
user_pref("userChrome.icon.global_menu",          true);
user_pref("userChrome.icon.global_menubar",       true);

// -- User Content -------------------------------------------------------------
user_pref("userContent.player.ui",             true);
user_pref("userContent.player.icon",           true);
user_pref("userContent.player.noaudio",        true);
user_pref("userContent.player.size",           true);
user_pref("userContent.player.click_to_play",  true);
user_pref("userContent.player.animate",        true);

user_pref("userContent.newTab.field_border",   true);
user_pref("userContent.newTab.full_icon",      true);
user_pref("userContent.newTab.animate",        true);
user_pref("userContent.newTab.pocket_to_last", true);
user_pref("userContent.newTab.searchbar",      true);

user_pref("userContent.page.illustration",     true);
user_pref("userContent.page.proton_color",     true);
user_pref("userContent.page.dark_mode",        true); // Need proton_color
user_pref("userContent.page.proton",           true); // Need proton_color

// ** Useful Options ***********************************************************
// Integrated calculator at urlbar
user_pref("browser.urlbar.suggest.calculator", true);

// Integrated unit convertor at urlbar
// user_pref("browser.urlbar.unitConversion.enabled", true);

// Draw in Titlebar
// user_pref("browser.tabs.drawInTitlebar", true);
// user_pref("browser.tabs.inTitlebar",        1); // Nightly, 96 Above

// ** Scrolling Settings *******************************************************
// == Only Sharpen Scrolling ===================================================
//         Pref                                             Value      Original
/*
user_pref("mousewheel.min_line_scroll_amount",                 10); //        5
user_pref("general.smoothScroll.mouseWheel.durationMinMS",     80); //       50
user_pref("general.smoothScroll.currentVelocityWeighting", "0.15"); //   "0.25"
user_pref("general.smoothScroll.stopDecelerationWeighting", "0.6"); //    "0.4"
*/

// == Smooth Scrolling ==========================================================
// ** Scrolling Options ********************************************************
// based on natural smooth scrolling v2 by aveyo
// this preset will reset couple extra variables for consistency
//         Pref                                              Value                 Original

user_pref("apz.allow_zooming",                               true);            ///     true
user_pref("apz.force_disable_desktop_zooming_scrollbars",   false);            ///    false
user_pref("apz.paint_skipping.enabled",                      true);            ///     true
user_pref("apz.windows.use_direct_manipulation",             true);            ///     true
user_pref("dom.event.wheel-deltaMode-lines.always-disabled", true);            ///    false
user_pref("general.smoothScroll.currentVelocityWeighting", "0.12");            ///   "0.25" <- 1. If scroll too slow, set to "0.15"
user_pref("general.smoothScroll.durationToIntervalRatio",    1000);            ///      200
user_pref("general.smoothScroll.lines.durationMaxMS",         100);            ///      150
user_pref("general.smoothScroll.lines.durationMinMS",           0);            ///      150
user_pref("general.smoothScroll.mouseWheel.durationMaxMS",    100);            ///      200
user_pref("general.smoothScroll.mouseWheel.durationMinMS",      0);            ///       50
user_pref("general.smoothScroll.mouseWheel.migrationPercent", 100);            ///      100
user_pref("general.smoothScroll.msdPhysics.continuousMotionMaxDeltaMS", 12);   ///      120
user_pref("general.smoothScroll.msdPhysics.enabled",                  true);   ///    false
user_pref("general.smoothScroll.msdPhysics.motionBeginSpringConstant", 200);   ///     1250
user_pref("general.smoothScroll.msdPhysics.regularSpringConstant",     200);   ///     1000
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaMS",         10);   ///       12
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio",  "1.20");   ///    "1.3"
user_pref("general.smoothScroll.msdPhysics.slowdownSpringConstant",   1000);   ///     2000
user_pref("general.smoothScroll.other.durationMaxMS",         100);            ///      150
user_pref("general.smoothScroll.other.durationMinMS",           0);            ///      150
user_pref("general.smoothScroll.pages.durationMaxMS",         100);            ///      150
user_pref("general.smoothScroll.pages.durationMinMS",           0);            ///      150
user_pref("general.smoothScroll.pixels.durationMaxMS",        100);            ///      150
user_pref("general.smoothScroll.pixels.durationMinMS",          0);            ///      150
user_pref("general.smoothScroll.scrollbars.durationMaxMS",    100);            ///      150
user_pref("general.smoothScroll.scrollbars.durationMinMS",      0);            ///      150
user_pref("general.smoothScroll.stopDecelerationWeighting", "0.6");            ///    "0.4"
user_pref("layers.async-pan-zoom.enabled",                   true);            ///     true
user_pref("layout.css.scroll-behavior.spring-constant",   "250.0");            ///   "250.0"
user_pref("mousewheel.acceleration.factor",                     3);            ///       10
user_pref("mousewheel.acceleration.start",                     -1);            ///       -1
user_pref("mousewheel.default.delta_multiplier_x",            100);            ///      100
user_pref("mousewheel.default.delta_multiplier_y",            100);            ///      100
user_pref("mousewheel.default.delta_multiplier_z",            100);            ///      100
user_pref("mousewheel.min_line_scroll_amount",                  0);            ///        5
user_pref("mousewheel.system_scroll_override.enabled",       true);            ///     true <- 2. If scroll too fast, set to false
user_pref("mousewheel.system_scroll_override_on_root_content.enabled", false); ///     true
user_pref("mousewheel.transaction.timeout",                  1500);            ///     1500
user_pref("toolkit.scrollbox.horizontalScrollDistance",         4);            ///        5
user_pref("toolkit.scrollbox.verticalScrollDistance",           3);            ///        3


```
</details>
 
**Additional context**
I am using these things alongside -- >
* https://github.com/mbnuqw/sidebery -- To get Vertical SideBar
* https://github.com/drannex42/FirefoxSidebar -- To make Sidebery into a single colum like Edge vertical Tabs
* https://github.com/joelshepherd/tabliss -- To customize Home page

**Comment by PhoenixCODE2322** [comment]
Also this is happening in Tablisis Extension , The `Add new widget` is not expanding ( a rectangular squares appears below)  . Any idea ?
![image](https://user-images.githubusercontent.com/75798544/200253859-de5b3b2c-31f9-4726-a44f-2c67cc568a21.png)

**Comment by black7375** [comment]
Do you use last commit?
This problem should have been solved almost mostly in #501

**Comment by PhoenixCODE2322** [comment]
> Do you use last commit? This problem should have been solved almost mostly in #501

My bad i missed the release . It worked . Thank you.

Anyidea about this https://github.com/black7375/Firefox-UI-Fix/issues/503#issuecomment-1305205078

**Comment by black7375** [comment]
`Tablisis` problem will be checked by the weekend.

**Comment by PhoenixCODE2322** [comment]
ThankYou.

**Comment by black7375** [comment]
Is there a special advantage of [rannex42/FirefoxSidebar](https://github.com/drannex42/FirefoxSidebar)?
This project has some support vertical bar. (If there is a deficiency, I can consider it in the next major version.)

https://github.com/black7375/Firefox-UI-Fix/wiki/Show-Off-Your-Config#vertical-tab

**Comment by black7375** [comment]
It's strange. It looks normally in my environment.
![image](https://user-images.githubusercontent.com/25581533/201510411-ff2d6dec-c27c-4bf6-8e26-df0406323f22.png)

**Comment by PhoenixCODE2322** [comment]
> It's strange. It looks normally in my environment. ![image](https://user-images.githubusercontent.com/25581533/201510411-ff2d6dec-c27c-4bf6-8e26-df0406323f22.png)

finally figured it out .. tried to switch on/off options in user.js and this is what was causing the problem. `user_pref("userChrome.hidden.disabled_menu",                true);`

**Comment by black7375** [comment]
Surprisingly, it occurs if the `#ContentSelectDropdownPopup`'s first `menuitem` is `disabled`.

![Screenshot_20221113_190609](https://user-images.githubusercontent.com/25581533/201516446-c1e06714-46e4-4bb2-99c0-5eb0cc500b9d.png)

Using `visibility: collapse` seems to work normally.

**Comment by PhoenixCODE2322** [comment]
> Is there a special advantage of [rannex42/FirefoxSidebar](https://github.com/drannex42/FirefoxSidebar)? This project has some support vertical bar. (If there is a deficiency, I can consider it in the next major version.)
> 
> https://github.com/black7375/Firefox-UI-Fix/wiki/Show-Off-Your-Config#vertical-tab

really sorry for not replying to this, i did not receive any notification for this message, also checked my notifications of github and this was not logged there. 



<details>
  <summary>Here are the recordings --></summary>

1.  Only Lepton And Sidebery Json (provided by the https://github.com/drannex42/FirefoxSidebar) (contains css for sideberry)
     Sideberry has inbuilt support for CSS in its setting>styles Editor

https://user-images.githubusercontent.com/75798544/201517465-f46658e1-4f07-49f1-8bbc-2ab904f0b2bc.mp4

2.  Only Leptop

https://user-images.githubusercontent.com/75798544/201517471-a0daf4e6-690e-438d-a72c-71581ed170a6.mp4

3.  Only (https://github.com/drannex42/FirefoxSidebar) with sideberry json provided by the same dev

https://user-images.githubusercontent.com/75798544/201517478-3af7efe5-3f58-491e-a76a-b7ddbe9b7fde.mp4

4. Both Leptop and https://github.com/drannex42/FirefoxSidebar

https://user-images.githubusercontent.com/75798544/201517486-40bdd358-ccd8-44fe-93ec-8ca7bcc54733.mp4

</details>


<details>
 <summary>Here is the `css` provided by the FirefoxSidebar dev</summary>

```css
#root {
  --nav-btn-height: 34.5px !Important;
  --tabs-height: 38px !Important;
  --tabs-spacing: 4px; */ Spacing between the tabs, be sure to change the tab height for it to look right!) */
  --tabs-indent: 10px !important;
  --tabs-font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;
}

@media (prefers-color-scheme:light) {
  #root {
     --bg: #f7f6f6 !important; /* Sideberry background color (follow instruction in userChrome.css):: default: #fff  */

     --tabs-fg: #323232 !important; /* Font color :: default: #323232 */
     --tabs-bg-hover: #dedddaff !important; /* Tab background on hover :: default: #dedddaff */
     --tabs-activated-bg: transparent !important; /* Active tab :: default :: transparent */
     --tabs-activated-shadow: 0px 5px 10px rgba(0,0,0,0.15); !important; /* Active tab shadow :: default: 0px 5px 10px rgba(0,0,0,0.15); */

     --btn-fg: #555 !important; /* Button main color :: default: #555; */
     --nav-btn-fg: var(--btn-fg) !important; /* Nav Button main color :: default: var(--btn-fg); */
    --border-color: rgba(0,0,0,0.1);
 }
}

@media (prefers-color-scheme:dark) {
  #root {
     --bg: #2b2a33 !important;  /* Sideberry background color (follow instruction in userChrome.css):: default: #2b2a33 */

     --tabs-fg: #fff !important; /* Font color :: default: #323232 */
     --tabs-bg-hover: rgba(255,255,255,0.135) !important; /* Tab background on hover :: default: rgba(255,255,255,0.1) */
     --tabs-activated-bg: var(--tabs-bg-hover) !important; /* Active tab :: default: var(--tabs-bg-hover) */
     --tabs-activated-shadow: none; !important; /* Active tab shadow :: default: none */

     --btn-fg: #fff !important; /* Button main color :: default: #fff; */
     --nav-btn-fg: var(--btn-fg) !important; /* Nav Button main color :: default: var(--btn-fg); */
    --border-color: rgba(0,0,0,0.15);
  }

  /* These exist for the bookmarks panel, not changed for light schemes */
  #root { 
     --bookmarks-folder-expanded-fg: #fff !important;
     --bookmarks-node-title-fg: #fff !important;
     --favicons-placeholder-bg: #fff !important;
     --bookmarks-folder-closed-fg: #fff !important;
     --bookmarks-folder-expanded-fg-hover: #ccc !important;
     --bookmarks-node-title-fg-hover: #ccc !important;
     --favicons-placeholder-bg-hover: #ccc !important;
     --bookmarks-folder-closed-fg-hover: #ccc !important;
  }
}



@media screen and (max-width: 60px) {
  #root {
    --tabs-indent: unset !important;
  }

  .container { 
      max-width: 60px;
  } 

  .Tab .audio {
    margin-left: -15px;
    transform: scale(.80);
    z-index: 99 !important;
  }

    .Tab[data-lvl] , .PinnedTab[data-lvl]  {
      max-width: 30px;
      float: left;
  }
    .container { 
      margin: 0px !important;
      max-width: 50px;
    }

    .Tab[data-lvl] , .PinnedTab[data-lvl]  {
      max-width: 30px;
      float: left;
  }

    .panel-btn[data-active="true"] {
        display: ;
        display: flex !important;
        position: absolute !important;
        background: none !important;
    }


    .panel-btn {
        display: none !important;
    }

    .Sidebar .settings-btn {
    display: none;
    }

    .container::after { 
    margin-left: 16px;
    }
}


.Sidebar .panel-box {
  border-bottom: 2px solid var(--border-color) !important;
}

.Sidebar {
  font-family: var(--tabs-font);
}

.container {
  padding-top: 2.5px !important;
  margin: 0 auto !important;
  max-width: calc(100% - 20px);
}

.NavigationBar {
   padding-left: 8px;
}

.Sidebar .settings-btn {

}


/* Reset default styles */
.Tab[data-active], .Tab:hover, .PinnedTab[data-active], .PinnedTab:hover {
  background-color: transparent;
  box-shadow: none !Important;
}

.Tab[data-active] .lvl-wrapper:after, .PinnedTab[data-active] {
  background-color: var(--tabs-activated-bg);
}


/* Style for Tabs and Pinned Tabs */
.Tab .lvl-wrapper:after, .PinnedTab {
  border-radius: 5px;
  border: 1px solid transparent !important;
  border-radius: 5px;
  text-align: left;
  transition: width 0.1s !Important;
}

/* Background layer for tabs */
.Tab .lvl-wrapper:after {
  content: '';
  position: absolute;
  top: 0px;
  left: 2px;
  margin: var(--tabs-spacing) 0;
  width: calc(100% - 4px);
  height: calc(100% - calc(var(--tabs-spacing) * 2));
  z-index: -1;
}

/* Style for pinned tabs */ 

.PinnedTab {
  height: calc(var(--tabs-height) - calc(var(--tabs-spacing) * 2)) !important; 
  margin: var(--tabs-spacing) 10px;
}

.Tab {
  border-radius: 5px; 
}


.Tab[data-active] .lvl-wrapper:after, .PinnedTab[data-active] {
   box-shadow: var(--tabs-activated-shadow) !important;
}

.Tab:hover .lvl-wrapper:after, .PinnedTab:hover {
  background: var(--tabs-bg-hover);
}

.Tab[data-active]:hover .lvl-wrapper:after {
  box-shadow: none !Important;
}

/*  Favicon Settings */

.Tab .fav, .PinnedTab .fav {
    position: relative;
    width: 18px;
    height: 18px;
    flex-shrink: 0;
    margin: 0 6px 0 7px;
    opacity: 1 !important;

}

.Tab .placeholder > svg {
  width: 18px;
  height: 18px;
  fill: var(--btn-fg);
;}

.PinnedTab  .fav {
     margin-left: 4px;
}

.Tab:hover  .fav, .PinnedTab:hover  fav {
    opacity: 1 !important;
}

.Tab  .placeholder, .PinnedTab . placeholder {
}


/* Internal Tab Settings */ 
.Tab  .t-box, .PinnedTab  .title {
    mask: linear-gradient(-90deg,transparent,#000 25px,#000);
  /*! display: none; */
}

.Tab  .t-box .title, .PinnedTab  .title {
padding-left: 4px;
font-family: var(--tabs-font) !important;
color: var(--tabs-fg);
}

/* Tab Close and Context Buttons */
.Tab  .close {
    fill: var(--btn-fg);
}

.Tab  .close > svg {
    fill: var(--btn-fg);
    background: none;
    opacity: 1;
    height: 18px !important;
width: 18px !important;
}

.Tab  .close > svg:hover {
    background: rgba(0,0,0,0.075);
    border-radius: 4px;
}

.PinnedTab  .close {
display: none !important;
}

.Tab  .ctx,
.PinnedTab  .ctx {
top: 4px;
right: auto;
left: -11px;
width: 4px;
height: calc(100% - 5px);
}

.Sidebar {
margin-top: -2.5px;
}



.PinnedDock {
padding-top: 2.5px !important;
padding-bottom: 0 !important;
margin-bottom: -2.5px;
}

.PinnedDock::after {
    display: none !important;
}

.Sidebar .panel-btn > svg, .Sidebar .panel-btn > img, .HiddenPanelsBar .hidden-panel > img, .HiddenPanelsBar .hidden-panel > svg {
  fill: var(--nav-btn-fg) !important;
}

.Sidebar .panel-btn .len {
  top: 6px !important;
}

.audio {
    position: absolute;
    margin-left: -14px;
    margin-top: 7px;
    z-index: 10;
}

.audio svg {
    padding: 3px;
    height: 14px !important;
    width: 14px !important;
    background: #fff;
    border-radius: 50%;
    box-shadow: 1px 1px 5px rgba(0,0,0,0.25);

}

.Tab[data-audible]  .t-box, .Tab[data-muted] .t-box {
    transform: none !important;
}
```


</details>

If you can add inbuilt support for Sideberry , It will be awesome. I like the sliding animation provided by leptop for sidebars. ( Should i create a new issue for sideberry support ?)

Optional Additional Request --> it would be cool that if sidebar can adapt or merge ( color/apearance/effects) in some way with the wallpaper on the right side.
or
If sidebar can be set to autohide like NavBar and TopBar and appears when mouse touches the left edge of the screen . To give a full imersive experience.
