### ISSUE TITLE
Increase Sidebar Size

### ISSUE THREAD

**Issue by KAGEYAM4** [black7375/Firefox-UI-Fix#518]
**Is your feature request related to a problem?**
I use sideberry , and i changed some of its internal available option, now the sidebar width seems o be small.

**The solution I'd like**
Any way to increase the sidebar width.
i tried this , by pasting it in `userContent.css` but did not worked.
```css
#sidebar {
	max-width: none !important;
	min-width: 0px !important; 
}
```

**Screenshots or video**
![image](https://user-images.githubusercontent.com/75798544/204617599-7b6bb405-590f-4339-82e6-07e9dff0f9dc.png)
