### ISSUE TITLE
Not working with Firefox 108

### ISSUE THREAD

**Issue by dvoraking** [black7375/Firefox-UI-Fix#532]
I cleared the startup cache

**Comment by Clouud9** [comment]
Seems to be an issue with a specific line of code:
```css
#tabbrowser-arrowscrollbox {
    position: absolute;
}
```
in `leptonChrome.css`

I'm not a css expert, I just found the answer on reddit (thank you [u/Mr_Crabman](https://old.reddit.com/r/firefox/comments/zkwuss/firefox_1080_released/j03zc3s/)), but you can change it from absolute to sticky, relative or static and it will fix itself. The other positions may work as well. It's probably safe to delete it as well.
