### ISSUE TITLE
Divide lines at unselected tabs

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#6]
from [Reddit comment](https://www.reddit.com/r/firefox/comments/ndqd2n/proton_fix_landing_icons/gycz0bs?utm_source=share&utm_medium=web2x&context=3)

**Describe the bug**
Missing the divide lines between inactive tabs.

**Environment (please complete the following information):**
 - Firefox Version: 89 beta 13

**Comment by black7375** [comment]
Reimplement it.

https://github.com/black7375/Firefox-UI-Fix/commit/2649a20658c98a9409ef2e6c62188675e5093730#diff-2f47ee8e5f8520c45fa369ed4e435af21b8273494d3d81eaa9b72ed77ca2f635

If that doesn't work, you can try a compatibility solution. (The shape is less pretty instead)

**Comment by black7375** [comment]
Will be rollback..

Most of the implements work in `nightly`, but it is not easy to guarantee backwards compatibility.
```css
  .tab-content::before,
  .tab-content::after {
    /* Box Model */
    content:  "" !important;
    display:  block !important;
    position: absolute !important;
    transform: translateY(-10px) !important;

    /* Bar shape */
    width:  1px  !important;
    height: 20px !important;

    /* Color */
    background-color: var(--toolbarseparator-color) !important;
    opacity: 0 !important;
    transition: opacity .2s var(--ease-basic) !important;
  }

  .tab-content::before {
    left: -2px !important;
  }
  .tab-content::after {
    right: -2.5px !important;
  }

  .tabbrowser-tab[visuallyselected] + .tabbrowser-tab[style*=transform] .tab-content::after,
  .tabbrowser-tab[style*=transform]:not([visuallyselected]) .tab-content::before,
  .tabbrowser-tab[style*=transform] + .tabbrowser-tab:not([visuallyselected]) .tab-content::before,
  .tabbrowser-tab:not([visuallyselected]):not(:hover):not([multiselected]) + .tabbrowser-tab:not([visuallyselected]):not(:hover):not([multiselected]) .tab-content::before,
  #tabbrowser-tabs[hasadjacentnewtabbutton]:not([overflow]) .tabbrowser-tab[last-visible-tab]:not([visuallyselected]):not(:hover):not([multiselected]) .tab-content::after {
    opacity: var(--tab-separator-opacity) !important;
  }
```
