### ISSUE TITLE
Bookmarks toolbar folder items double spaced

### ISSUE THREAD

**Issue by Dan0268** [black7375/Firefox-UI-Fix#68]
The fix is doing its job on the tab bar and search bar etc. but when I click on a folder in the bookmarks toolbar the items in that folder dropdown menu are still double spaced and chunky. Is it possible to make them single spaced like it is in the history and bookmarks side menu?
![Double spaced bookmarks](https://user-images.githubusercontent.com/31425080/120932457-2bfd0e80-c739-11eb-935b-6b3737c555f3.png)

**Comment by black7375** [comment]
I mostly work on Linux, and I didn't even think of it because I don't use the bookmarks toolbar very well.

Note that in Linux, it looks like a native menu.
![image](https://user-images.githubusercontent.com/25581533/120944589-dc144c80-c724-11eb-9bec-b4ce233be566.png)

**Comment by Dan0268** [comment]
Fair enough. Only raising it because everywhere they suggest to turn browser.proton.contextmenus.enabled (in about:config) to false. That does remove the double spacing but also the theme functionality, as in, in my case it goes with light theme for the menus. Would be great to keep the dark theme and also change the spacing. (the full dark theme integration is about the only feature I actually want from the update tbh).

![image](https://user-images.githubusercontent.com/31425080/120960653-a6f91000-c79f-11eb-831c-82fecb3429cd.png)

**Comment by SimYunSup** [comment]
If you want to decrease menuitem padding in bookmark folder like image below, Try to add this CSS on `userChrome.css`

![image](https://user-images.githubusercontent.com/47362439/121781488-fb592100-cbdf-11eb-937f-9ed879b5e460.png)

```css
@media (-moz-os-version: windows-win10) {
    :root:not([uidensity="touch"]) menupopup > menuitem.bookmark-item, 
    :root:not([uidensity="touch"]) menupopup > menuitem.openintabs-menuitem {
      padding-block: 0.2em !important;
      padding-inline-start: 0.5em !important;
    }
    :root:not([uidensity="touch"]) menupopup > .bookmarks-actions-menuseparator {
      margin: 2px 0.25em !important;
    }
  }
```
