### ISSUE TITLE
UserChrome.css option to hide Unified Extensions and Overflow Menu Button

### ISSUE THREAD

**Issue by kungfubeaner** [black7375/Firefox-UI-Fix#702]
### Is your feature request related to a problem?

Many people including myself like to hide the overflow menu and unified extensions button and I edit UserChrome.css everytime I upgrade Firefox UI fix so I have to be careful to save a copy each time.

### The solution I'd like

I would like it if UserChrome.css came with these two lines commented out in order to be able to just uncomment them to enable the feature:

```css
/* Hide Overflow Menu button */
#PlacesChevron { display: none !important; }

/* Hide Unified Extensions button */
#unified-extensions-button, #unified-extensions-button > .toolbarbutton-icon {
	width: 0px !important;
	padding: 0px !important;
}
```

### Additional context

Overflow menu button shows up randomly when you have your bookmarks toolbar next to your extensions icon in the toolbar.  I have a folder with links/bookmarks in my toolbar for easy access which triggers that bug with the overflow menu button.

**Comment by 2641a40fd44383320adde4b027a1d0b03bd550** [comment]
maybe there should be a list of buttons you can't remove in userChrome.css, i.e.
```css
/* Navigation bar */
#PlacesChevron, /* Overflow menu */
#PanelUI-button, /* Application menu */
#unified-extensions-button, /* Extensions */

/* URL bar */
#tracking-protection-icon-container, /* Tracking protection */
#pageActionButton, /* Page actions */
#star-button-box /* Bookmark this page */
{
  display: none !important;
}
```
