### ISSUE TITLE
Add icon to "Private Container" link contextmenu & Tab contextmenu

### ISSUE THREAD

**Issue by surapunoyousei** [black7375/Firefox-UI-Fix#774]
### Is your feature request related to a problem?

This feature request relate to Floorp code.

### The solution I'd like

Add these code to Floorp specific Lepton code.

```CSS

#context_toggleToPrivateContainer {
    --menuitem-image: url("chrome://browser/skin/lepton/private-favicon.svg");      
}

#open_in_private_container {
    --menuitem-image: url("chrome://browser/skin/lepton/private-favicon.svg");
}

```

### Screenshots or video

![image](https://github.com/black7375/Firefox-UI-Fix/assets/73892113/164e7734-3916-43f6-9b79-abf6a66e91a7)

### Additional context

I will add this feature at 11.4.0
