### ISSUE TITLE
New Tab button appears unusually large

### ISSUE THREAD

**Issue by Sollace** [black7375/Firefox-UI-Fix#777]
### Describe the bug

See attachment.

This is something that I have experienced with [Floorp](https://github.com/Floorp-Projects/Floorp) which incorporates Lepton, however I believe the issue may be originating from here as I see Lepton doing something to the styling of the new tab button. (specifically it overrides the border radius and padding):

(leptonChrome.css)

```css
  /* '+'Icon */
  #tabs-newtab-button .toolbarbutton-icon {
    border-radius: var(--tab-border-radius) var(--tab-border-radius) 0 0 !important; /* Original: var(--tab-border-radius) */
    padding: calc(var(--toolbarbutton-inner-padding) - var(--tab-block-margin) / 4) var(--toolbarbutton-inner-padding)
      calc(var(--toolbarbutton-inner-padding) + var(--tab-block-margin) / 4 + var(--uc-tabs-navbar-shadow-size)) !important;
    -moz-context-properties: fill, fill-opacity;
    fill: var(--toolbarbutton-icon-fill);
    fill-opacity: var(--toolbarbutton-icon-fill-opacity);
  }
  ```

The temporary "fix" I worked out for my userChrome.css is as follows:

```css
    #tabs-newtab-button image {
        /* Fix new tab button appearing unusually large */
        padding: 5px !important; /*make icon smaller*/
        margin: 3px; /*add spacing around the outside of the icon*/
        margin-top: 5px; /*moved down to vertically center the button*/
        border-radius: 4px !important; /*add border radius to be consistent with other UI elements*/
        width: calc(2 * var(--toolbarbutton-inner-padding) + 10px) !important; /*10 changed from 16*/
        height: calc(2 * var(--toolbarbutton-inner-padding) + 10px) !important; /*10 changed from 16*/
    }
```

### Screenshots

What it looks like without the "fix":
![image](https://github.com/black7375/Firefox-UI-Fix/assets/6429283/ba3bc9b9-9b16-4744-b2b4-2c5f30488a54)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/6429283/0ca8183d-0e49-40a3-8cbb-19dff77b9780)

What it looks like with the "fix":
![image](https://github.com/black7375/Firefox-UI-Fix/assets/6429283/a1e11532-45d7-4761-9da2-67fbb186a573)

### OS

Linux, Windows 10

### Firefox Version

11.3.3 

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
Hello, what's your version of floorp?
In my floorp(`11.3.3`, `20230914032237`) doesn't have that problem.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/aeed73c9-07d8-4ef6-a411-e2d1e836bc57)

**Comment by Sollace** [comment]
> Hello, what's your version of floorp? In my floorp(`11.3.3`, `20230914032237`) doesn't have that problem.
> 
> ![image](https://user-images.githubusercontent.com/25581533/270086783-aeed73c9-07d8-4ef6-a411-e2d1e836bc57.png)

11.3.3 installed via flatpak. I noticed it start after it updated a few days ago, but I was behind on updates for a while. On windows I've had it a fair while longer since that one was installed after the linux one.

**Comment by Sollace** [comment]
My lepton settings for comparison.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/6429283/07d0a391-6186-4f52-a7ff-dcb04ef3d28e)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/6429283/e77e3cde-2861-4728-a37a-d31e170e8fa1)

**Comment by Sollace** [comment]
I will note that I'm using Manjaro/KDE. Despite that, the flatpak version is still using the Gnome window decorations, which may play a part in it.

**Comment by surapunoyousei** [comment]
Sorry for the delay in finding this issue.

I was aware of this issue and was investigating whether we could resolve it. This seems to occur in Windows as well, and is more likely to be found when multi-tab is enabled.

**Comment by surapunoyousei** [comment]
Maybe relate issue.

https://github.com/Floorp-Projects/Floorp/issues/493

**Comment by surapunoyousei** [comment]
```CSS

  @supports not -moz-bool-pref("userChrome.tab.photon_like_padding") {
    @supports -moz-bool-pref("userChrome.tab.lepton_like_padding") {
      .tabbrowser-tab[pinned] {
        padding-inline: 1px !important;
      }
      .tabbrowser-tab:not([pinned]) {
        margin-inline: -1px !important;
      }
    }
    @supports not -moz-bool-pref("userChrome.tabbar.multi_row") {
      #TabsToolbar:not([multibar]) .tabbrowser-tab:not(:last-of-type) {
        margin-inline-end: -2px !important;
      }
    }
  }
  
  ```

I found the cause. This CSS have the problem
