### ISSUE TITLE
If there is blank on the nav-bar and using nav-bar hide click on the position on browsing area where the blank is occurpied when nav-bar is showing equals click on the window title bar

### ISSUE THREAD

**Issue by 117649** [black7375/Firefox-UI-Fix#820]
### Describe the bug

When using auto hide nav bar click on place on the view port where is the blank space (e.g. flexible spacer) on navbar when the nav bar is expanded will also be count as click on the tittle bar. Double click at these places also down size or expand the browser window. The window can be dragged when dragging at such places.

### Screenshots

![image](https://github.com/black7375/Firefox-UI-Fix/assets/8281345/135a001b-09cf-400e-83c6-7fad50e834db)
When right click on the place where the flexible spacer is when nav bar is expanded you can see tittle bar context menu is opened behind page context menu.
Double click on the area will cause FF window to change its size too.

![image](https://github.com/user-attachments/assets/0da97ca9-fe5f-4d94-b8c5-07f7fc6bc154)
Use the flexbox overlay to show the clicked place.

### OS

Windows 10

### Firefox Version

119.0.1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [x] Light
- [x] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by 117649** [comment]
```css
@-moz-document url(chrome://browser/content/browser.xhtml)
{
  @media (-moz-bool-pref: "userChrome.autohide.tabbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")),
    (-moz-bool-pref: "userChrome.autohide.tabbar") and (-moz-bool-pref: "userChrome.tabbar.one_liner") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")),
    (-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")),
    (-moz-bool-pref: "userChrome.autohide.navbar") and (-moz-bool-pref: "userChrome.tabbar.one_liner") and (-moz-bool-pref: "userChrome.autohide.navbar") and (not (-moz-bool-pref: "userChrome.tabbar.one_liner")) {
    #nav-bar:not([customizing]) toolbarspring {
      visibility: collapse;
    }

    #navigator-toolbox:is(:hover, :focus-within)
      #nav-bar:not([customizing])
      toolbarspring {
      visibility: visible;
    }
  }
}
```

Found out this style can fix it @black7375.

**Comment by black7375** [comment]
Thanks for your effort.
I'm about to go to bed today, so I'll test it tomorrow after work.

**Comment by 117649** [comment]
> Thanks for your effort. I'm about to go to bed today, so I'll test it tomorrow after work.

@black7375 I just make some adjustment to the transition so the movement should not be visible.

```cs
  #nav-bar:not([customizing]) toolbarspring {
    transition-delay: 0s !important;
  }
  
  #mainPopupSet:not(:hover) ~ #navigator-toolbox:not(:hover, :focus-within) #nav-bar:not([customizing]) toolbarspring {
    margin-left: -56px;
    margin-right: -56px;
    will-change: margin-right, margin-left;
    transition: margin-right 0s var(--animation-easing-function)
      calc(var(--uc-autohide-toolbar-delay) + var(--uc-autohide-toolbar-speed)),
      margin-left 0s var(--animation-easing-function)
      calc(var(--uc-autohide-toolbar-delay) + var(--uc-autohide-toolbar-speed)) !important;
  }
```

I set the margin on both side because I'm not sure what happens when spacer is at different edge of the nav-bar.
For most time the url bar should expand and fill the gap.

**Comment by 117649** [comment]
> > Thanks for your effort. I'm about to go to bed today, so I'll test it tomorrow after work.
> 
> @black7375 I just make some adjustment to the transition so the movement should not be visible.
> 
> ```cs
>   #nav-bar:not([customizing]) toolbarspring {
>     transition-delay: 0s !important;
>   }
>   
>   #mainPopupSet:not(:hover) ~ #navigator-toolbox:not(:hover, :focus-within) #nav-bar:not([customizing]) toolbarspring {
>     margin-left: -56px;
>     margin-right: -56px;
>     will-change: margin-right, margin-left;
>     transition: margin-right 0s var(--animation-easing-function)
>       calc(var(--uc-autohide-toolbar-delay) + var(--uc-autohide-toolbar-speed)),
>       margin-left 0s var(--animation-easing-function)
>       calc(var(--uc-autohide-toolbar-delay) + var(--uc-autohide-toolbar-speed)) !important;
>   }
> ```
> 
> I set the margin on both side because I'm not sure what happens when spacer is at different edge of the nav-bar. For most time the url bar should expand and fill the gap.

@black7375 This still left some gaps caused by other element's margin thus I've thought about another way.
Pad hamburger button to cover everything.

```css
  #nav-bar:not([customizing]) #PanelUI-button {
    transition-delay: 0s !important;
  }
  
  #mainPopupSet:not(:hover) ~ #navigator-toolbox:not(:hover, :focus-within) #nav-bar:not([customizing]) #PanelUI-button {
    padding-left: 100%;
    margin-left: -100%;
    will-change: padding-left, margin-left;
    transition: padding-left 0s var(--animation-easing-function)
      calc(var(--uc-autohide-toolbar-delay) + var(--uc-autohide-toolbar-speed)),
      margin-left 0s var(--animation-easing-function)
      calc(var(--uc-autohide-toolbar-delay) + var(--uc-autohide-toolbar-speed)) !important;
  }
```

**Comment by 117649** [comment]
@black7375 After some deep dive in to this I found all you really need is this:
```css
  #mainPopupSet:not(:hover)~#navigator-toolbox:not(:hover, :focus-within) #nav-bar:not([customizing]) {
    -moz-window-dragging: no-drag;
  }
```
So simple. Include that and we can finally close this.
