### ISSUE TITLE
[Question] FF 120: Restore menus native background color

### ISSUE THREAD

**Issue by Yaron10** [black7375/Firefox-UI-Fix#823]
### Is your feature request related to a problem?

```css
menu, menuitem, menucaption { appearance: auto !important; }
```

Used to work in FF 114.
What should I add/change in FF 120?

Windows 10.

Thank you.

### The solution I'd like

Restore menus native background color.
