### ISSUE TITLE
Firefox color not in the foreground

### ISSUE THREAD

**Issue by gabri25ele** [black7375/Firefox-UI-Fix#85]
When Firefox is not foreground the tab bar change in this (grey) way

![secondopiano](https://user-images.githubusercontent.com/33927879/121675137-49bcd180-cab3-11eb-92e5-c62e841e8a5f.png)

is there any parameter to adjust that behaviour? or does it depend on the theme chosen? (in my case of system)

**Comment by black7375** [comment]
I remember that the variable was not set at Proton.
It was `inactive` blahblah, but I think I should look for it.

**Comment by black7375** [comment]
I think it's possible with `:-moz-window-inactive`

![image](https://user-images.githubusercontent.com/25581533/121717657-f2c5f500-cad0-11eb-8422-b7ac03f70ae1.png)

```css
/* Custom code */
:root {
  --lwt-accent-color-inactive: aqua;
}

/* Firefox's code */
#navigator-toolbox:-moz-window-inactive:-moz-lwtheme {
  background-color: var(--lwt-accent-color-inactive, var(--lwt-accent-color));
}
```

**Comment by gabri25ele** [comment]
so it's not a mistake, is mozilla just like that?

> ```css
> /* Custom code */
> :root {
>   --lwt-accent-color-inactive: aqua;
> }
> 
> /* Firefox's code */
> #navigator-toolbox:-moz-window-inactive:-moz-lwtheme {
>   background-color: var(--lwt-accent-color-inactive, var(--lwt-accent-color));
> }
> ```

does this code need to be added to userChrome.css?
in any position?

**Comment by black7375** [comment]
`Firefox's code` is already set up, so you only need to customize `Custom code`.

like this.
```css
/* userChrome.css */
:root {
  --lwt-accent-color-inactive: aqua; /* YOUR COLOR */
}
```

**Comment by gabri25ele** [comment]
> /* userChrome.css */
> :root {
>   --lwt-accent-color-inactive: aqua; /* YOUR COLOR */
> }
> ```

also here, NOT work with **system theme** 😥

**Comment by black7375** [comment]
Change the code I posted above.

```css
#navigator-toolbox:-moz-window-inactive {
  background-color: aqua;
}
```
