### ISSUE TITLE
a small difference in hue

### ISSUE THREAD

**Issue by gabri25ele** [black7375/Firefox-UI-Fix#86]
![vuoto](https://user-images.githubusercontent.com/33927879/121706615-15a6d800-cad6-11eb-8cef-cd7880347e11.png)

the **tab background** color is **ffffff**

![tab](https://user-images.githubusercontent.com/33927879/121706410-e3957600-cad5-11eb-8d54-3d9d27f11add.png)

instead the Firefox color background is f9f9fb

![sotto](https://user-images.githubusercontent.com/33927879/121706493-f7d97300-cad5-11eb-9748-c57a88d4458a.png)

can we fix this very slight difference in color almost imperceptible?

**Comment by black7375** [comment]
On my computer, both are in color `#F9F9FB`.
![image](https://user-images.githubusercontent.com/25581533/121715239-27847d00-cace-11eb-888d-ff5957c3f226.png)

Maybe it was fixed at the next commit!!
https://github.com/black7375/Firefox-UI-Fix/commit/8226cdd7b5a5d5e6305cb2e91cc3a9a648e72dad

Would you like to check it out?

**Comment by gabri25ele** [comment]
excuse me, but with the corrections, I don't see differences.
let me show you... I took a firefox portable, no changes, only insert the Lepton.zip v1.0 as well as
I checked the changes (https://github.com/black7375/Firefox-UI-Fix/commit/8226cdd7b5a5d5e6305cb2e91cc3a9a648e72dad)
but I always see the same
if you want to try, can download here:
https://krakenfiles.com/view/O2M95GvCmd/file.html

**Comment by black7375** [comment]
Would you like to try the latest `master`'s code?

**Comment by gabri25ele** [comment]
wait...
I noticed that the problem is only on the system theme selected...

dark theme and light theme are right

![dark](https://user-images.githubusercontent.com/33927879/121769418-bb545880-cb63-11eb-9a00-3079808505a6.png)
![light](https://user-images.githubusercontent.com/33927879/121769423-bf807600-cb63-11eb-87b3-c49898b8d601.png)

the color difference is using the theme system in Firefox

![system](https://user-images.githubusercontent.com/33927879/121769439-d921bd80-cb63-11eb-9d16-2405eafb5340.png)

**Comment by gabri25ele** [comment]
> 
> 
> Would you like to try the latest `master`'s code?

I don't know what it could be. 🙄

**Comment by black7375** [comment]
> I don't know what it could be. 🙄

It was meant to install Original in the following way:
https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide

---

Now, You don't have to.
I've checked that it only happens with the system theme. (by your comment)

**Comment by gabri25ele** [comment]
> I've checked that it only happens with the system theme. 

Unfortunately 😥

**Comment by black7375** [comment]
The strange thing only happens when the light theme is.
I will investigate.

**Comment by black7375** [comment]
It looks like this:
```css
:root:not(:-moz-lwtheme) {
  --tab-selected-bgcolor: rgb(255,255,255);
}

.tab-background[multiselected="true"], .tab-background[selected="true"] {
    border-top-color: var(--tabs-border-color);
    background-color: var(--tab-selected-bgcolor, var(--toolbar-bgcolor)); /**/
    background-image: var(--toolbar-bgimage);
    background-repeat: repeat-x;
}
```

It's probably been modified now.
