### ISSUE TITLE
Revert tab hover tooltips to how they were

### ISSUE THREAD

**Issue by lolcatw** [black7375/Firefox-UI-Fix#891]
### Is your feature request related to a problem?

In the past, hovering over a tab for a short period of time showed a system-styled hover box with the full title and URL of the webpage. Now, firefox shows a screenshot of the website, and there is no cooldown. As soon as you hover, you see the popup...

### The solution I'd like

Revert back to the system-styled hover box.

### Screenshots or video

This is NOT what I want. The previous version of FF did this correctly.
![Untitled](https://github.com/black7375/Firefox-UI-Fix/assets/107773509/ce02f325-2ec4-4432-8ac8-d816e490e0d7)

### Additional context

Just thought I'd throw this in there, if you want no padding in dialog boxes and no rounded borders like shown above, append the following CSS in userChrome.css

```css
menupopup{
	--panel-padding: 0 !important;
	--panel-border-radius: 0 !important;
}

#navigator-toolbox{
	animation:none !important;
	transition:none !important;
}

#context-sep-navigation,#context-navigation{display:none !important;}

*{border-radius:0 !important;}
```
