### ISSUE TITLE
If current tab select by Tab, box-shadow is duplicated with cyan color.

### ISSUE THREAD

**Issue by SimYunSup** [black7375/Firefox-UI-Fix#92]
**Describe the bug**
If current tab select by `Tab`, `box-shadow` is duplicated with cyan color.

**Expected behavior**
If selected tab select by `Tab`, `box-shadow` must be off.
Or, current tab border is implemented not by box-shadow.

**Screenshots**
![image](https://user-images.githubusercontent.com/47362439/121796685-fdf65d80-cc55-11eb-9b0e-537c65d37a65.png)

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by SimYunSup** [comment]
If css below is changed, It will be fixed.
Before
```css
#TabsToolbar[brighttext] #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab[visuallyselected="true"] > .tab-stack > .tab-background:-moz-lwtheme {
    /* Origina: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9))
       Bright: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9)), 0 0 4px rgba(128,128,142,0.5) */
    box-shadow: 0 0 1px var(--toolbar-color) !important;
  }
```
After
```
#TabsToolbar[brighttext] #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab[visuallyselected="true"]:not(:focus) > .tab-stack > .tab-background:-moz-lwtheme {
    /* Origina: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9))
       Bright: 0 0 1px var(--tab-line-color, rgba(128,128,142,0.9)), 0 0 4px rgba(128,128,142,0.5) */
    box-shadow: 0 0 1px var(--toolbar-color) !important;
  }
```
![image](https://user-images.githubusercontent.com/47362439/121797418-0d2bda00-cc5b-11eb-9579-ed8e9295ba11.png)

**Comment by black7375** [comment]
Is there a situation to make the cyan color happen?

**Comment by SimYunSup** [comment]
Make a new tab, and Push Tab button many times.

**Comment by black7375** [comment]
I checked.

```css
.keyboard-focused-tab > .tab-stack > .tab-background,
.tabbrowser-tab:focus:not([aria-activedescendant]) > .tab-stack > .tab-background {
  outline: var(--focus-outline);
  outline-offset: -2px;
}
```
