### ISSUE TITLE
White outline on the sides of tabs and across the top of the address bar.

### ISSUE THREAD

**Issue by TheReverend403** [black7375/Firefox-UI-Fix#99]
![Screenshot](https://dev.pste.pw/f/QwVbP.png)

**Environment:**
Firefox Version: 89.0
OS: Windows
Theme: Dark

**Comment by black7375** [comment]
It has been confirmed to appear in some themes.
```css
/* photon */
#navigator-toolbox:-moz-lwtheme {
    --tabs-border-color: rgba(0,0,0,.3);
}

/* proton */
:root {
  --tabs-border-color: threedshadow;
}
```

**Comment by TheReverend403** [comment]
They don't look intentional when compared to the exact same CSS on Linux. They're far more subtle compared to Windows where it's just a solid white line.

![screen](https://dev.pste.pw/f/Z4pBU.png)

**Comment by TheReverend403** [comment]
For the record, I've made some slight customisations to the photon-style branch, nothing that should affect borders between tabs though.

_userChrome.css is userChrome.css from this repo.

```css
@import url("_userChrome.css") screen;

:root {
    --autocomplete-popup-highlight-background: #8c54fe !important;
    --focus-outline-color: #8c54fe !important;
    --lwt-popup-brighttext-url-color: #b5b5b5 !important;
    --url-match-color: #fd971f;
}

/* .tabbrowser-tab:is([selected], [multiselected]) .tab-context-line { */
/*     background-color: var(--autocomplete-popup-highlight-background) !important; */
/* } */

#urlbar:is([focused]) > #urlbar-background, #urlbar-container .urlbar-input-box {
    border-color: var(--focus-outline-color) !important;
}

.urlbarView-row:not([selected]) .urlbarView-title strong,
.urlbarView-row:not([selected]) .urlbarView-url strong {
    color: var(--url-match-color) !important;
}
```

**Comment by black7375** [comment]
Oh, I checked. I will check it.

**Comment by black7375** [comment]
The surest way is to remove box-shadow.

```css
  #nav-bar {
    box-shadow: none !important;
  }
```

But some themes need `box-shadow`, so it will provided by wiki.
https://github.com/black7375/Firefox-UI-Fix/wiki/Compatibility-Issues-Solution#white-outline-on-the-top-of-address-bar
